//! Tauri application wiring: logging, the typed command bridge, and the builder.
//!
//! Keep this file about *registration* only. Command bodies live in
//! [`commands`], and the real logic lives in the `santree-core` crate.

mod agent;
mod commands;
mod commit_draft;
mod db;
mod error;
mod git;
mod git_watch;
mod github;
mod gql;
mod linear;
mod notes;
mod openers;
mod pr;
mod prompts;
mod repo;
mod reviews;
mod session;
mod settings;
mod terminal;
mod text_store;
mod worktree;

use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};

/// The app's concrete `tauri-specta` builder type (Tauri's default `Wry` runtime).
type AppBuilder = Builder<tauri::Wry>;

/// Where the generated TypeScript client is written, relative to `src-tauri`
/// (the cwd for both `tauri dev` and `cargo test`). Only used by the
/// debug-only `export_bindings`, so it's gated to avoid a dead-code warning in
/// release builds.
#[cfg(debug_assertions)]
const BINDINGS_PATH: &str = "../src/bindings.ts";

/// Build the `tauri-specta` command bridge.
///
/// Centralised so the binary (`run`), the debug export, and the `gen:bindings`
/// test all use the exact same command set — there's no way for them to drift.
fn specta_builder() -> AppBuilder {
    Builder::<tauri::Wry>::new()
        .events(collect_events![git_watch::WorktreeChanged])
        .commands(collect_commands![
        commands::list_repos,
        commands::add_repo,
        commands::list_agents,
        commands::agent_auth,
        commands::github_status,
        commands::worktrees,
        commands::base_worktree,
        commands::create_worktree,
        commands::remove_worktree,
        commands::run_worktree_setup_streamed,
        commands::pull_worktree,
        commands::update_base_branch,
        commands::worktree_status,
        commands::worktree_file_diff,
        commands::worktree_file_source,
        commands::worktree_files,
        commands::watch_worktrees,
        commands::stage_path,
        commands::unstage_path,
        commands::discard_path,
        commands::stage_all_paths,
        commands::unstage_all_paths,
        commands::commit_worktree,
        commands::commit_message,
        commands::commit_draft,
        commands::set_commit_draft,
        commands::set_worktree_title,
        commands::work_prompt,
        commands::agent_session,
        commands::pr_draft,
        commands::create_pull_request,
        commands::worktree_prs,
        commands::reviews,
        commands::pr_detail,
        commands::worktree_init_script,
        commands::set_worktree_init_script,
        commands::make_init_script_executable,
        commands::list_openers,
        commands::open_in_app,
        commands::list_triage_tickets,
        commands::triage_detail,
        commands::triage_set_state,
        commands::triage_schedule,
        commands::get_settings,
        commands::set_settings,
        commands::task_note,
        commands::set_task_note,
        commands::list_claude_commands,
        commands::get_setting,
        commands::set_setting,
        commands::resolve_setting,
        commands::linear_auth_status,
        commands::linear_orgs,
        commands::set_repo_linear_org,
        commands::linear_list_issues,
        commands::linear_connect,
        terminal::terminal_open,
        terminal::terminal_write,
        terminal::terminal_resize,
        terminal::terminal_close,
    ])
}

/// Write `src/bindings.ts` from the current command set.
///
/// Called from `run()` in debug builds and from the `export_bindings` test
/// (which is what `pnpm gen:bindings` drives).
#[cfg(debug_assertions)]
fn export_bindings(builder: &AppBuilder) -> anyhow::Result<()> {
    builder.export(
        specta_typescript::Typescript::default()
            .header("// @generated by tauri-specta. Do not edit by hand.\n"),
        BINDINGS_PATH,
    )?;
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
/// File + stdout logger. Rust (`log` facade) and forwarded JS-`console` logs land
/// in ONE attachable file at the OS log dir — on macOS
/// `~/Library/Logs/com.santree.desktop/santree.log` — each line carrying a local
/// timestamp, level, and source target (`[santree::linear]` for Rust,
/// `[webview]` for JS) so it's clear when, where, and what. Bounded to ~20 MB
/// (one 10 MB file + one rotated backup) so it can't grow without limit, and
/// stays small enough to attach to a bug report. `sqlx` is pinned to warn so
/// query chatter doesn't drown the file.
fn log_plugin() -> tauri::plugin::TauriPlugin<tauri::Wry> {
    use tauri_plugin_log::{Builder, RotationStrategy, Target, TargetKind, TimezoneStrategy};
    Builder::new()
        .targets([
            Target::new(TargetKind::Stdout),
            Target::new(TargetKind::LogDir {
                file_name: Some("santree".into()),
            }),
        ])
        .level(log::LevelFilter::Info)
        .level_for("sqlx", log::LevelFilter::Warn)
        .timezone_strategy(TimezoneStrategy::UseLocal)
        .max_file_size(10_000_000)
        .rotation_strategy(RotationStrategy::KeepOne)
        .build()
}

/// One-time migration after the bundle id rename (`com.santree.app` →
/// `com.santree.desktop`): the app data dir is keyed by the identifier, so move
/// the existing SQLite DB (and its WAL sidecars) from the old dir into the new one
/// so local state — repos, settings, Linear tokens, worktree links, terminal
/// sessions — survives the rename. No-op once the new DB exists, or if there's no
/// legacy DB to carry over. Logs are intentionally left behind (disposable).
fn migrate_legacy_data_dir(new_dir: &std::path::Path) {
    const LEGACY_ID: &str = "com.santree.app";
    if new_dir.join("santree.db").exists() {
        return; // already migrated (or a fresh install on the new id)
    }
    let Some(legacy_dir) = new_dir.parent().map(|p| p.join(LEGACY_ID)) else {
        return;
    };
    if !legacy_dir.join("santree.db").exists() {
        return; // nothing to migrate
    }
    if let Err(e) = std::fs::create_dir_all(new_dir) {
        log::warn!("data migration: couldn't create {}: {e}", new_dir.display());
        return;
    }
    // Move the DB and its WAL/SHM sidecars together (the app isn't using them yet).
    for name in ["santree.db", "santree.db-wal", "santree.db-shm"] {
        let from = legacy_dir.join(name);
        if from.exists() {
            if let Err(e) = std::fs::rename(&from, new_dir.join(name)) {
                log::warn!("data migration: couldn't move {name}: {e}");
            }
        }
    }
    log::info!(
        "migrated app data from {} to {}",
        legacy_dir.display(),
        new_dir.display()
    );
}

/// Merge a login-shell PATH into the current one: login entries first (the source
/// of truth for where the user's tools live), then any current-only entries we
/// shouldn't drop. Order-preserving and de-duplicated. Pure, for testability.
fn merge_paths(login: &str, current: &str) -> String {
    let mut seen = std::collections::HashSet::new();
    login
        .split(':')
        .chain(current.split(':'))
        .filter(|p| !p.is_empty() && seen.insert(*p))
        .collect::<Vec<_>>()
        .join(":")
}

/// Recover the user's real PATH at startup. A Finder-launched macOS bundle gets a
/// minimal PATH (`/usr/bin:/bin:/usr/sbin:/sbin`) that misses Homebrew, `direnv`,
/// version managers, etc. Every subprocess we spawn inherits this PATH — `git`
/// (and the repo's commit hooks, which routinely shell out to `direnv` and friends),
/// `.santree` setup scripts, the agent CLIs, openers — so without this they fail to
/// find tools that work fine in a terminal (e.g. the `direnv: command not found` a
/// pre-commit hook hits, which then breaks the hook's lint step). We merge the login
/// shell's PATH into the process PATH exactly once, before anything spawns, so all
/// children inherit it. No-op when launched from a terminal (login PATH already
/// covers the current one). Unix only; the probe spawns one login shell (~tens of ms).
#[cfg(unix)]
fn hydrate_path() {
    let Some(login) = settings::login_shell_path() else {
        return;
    };
    let current = std::env::var("PATH").unwrap_or_default();
    let merged = merge_paths(&login, &current);
    if !merged.is_empty() && merged != current {
        // Safe: called as the first thing in `run()`, before we spawn any threads
        // or the Tauri/async runtime, so there's no concurrent env access.
        std::env::set_var("PATH", &merged);
    }
}

pub fn run() {
    // Must run before any subprocess is spawned (git, hooks, setup scripts, agents).
    #[cfg(unix)]
    hydrate_path();

    let builder = specta_builder();

    // In debug builds, (re)generate `src/bindings.ts` on every run so the typed
    // client tracks the Rust commands during development. Release builds skip
    // this — the committed bindings are used as-is.
    #[cfg(debug_assertions)]
    export_bindings(&builder).expect("failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(log_plugin())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_decorum::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            // Wire specta-registered events into the app (none yet, but this is
            // where they'd attach as the app grows).
            builder.mount_events(app);

            // Open the app database and make the pool available to commands. The
            // bundle id was renamed (com.santree.app → com.santree.desktop); the
            // data dir is keyed by it, so carry the existing DB over first.
            let data_dir = app.path().app_data_dir().expect("resolving app data dir");
            migrate_legacy_data_dir(&data_dir);
            let db = tauri::async_runtime::block_on(db::init(data_dir.join("santree.db")))
                .expect("initializing database");
            app.manage(db);

            // Owns all live terminal sessions; commands read it from state.
            app.manage(santree_pty::PtyManager::new());

            // Owns the worktree filesystem watcher; `watch_worktrees` points it at
            // the active repo so the Trees views refresh live on disk changes.
            app.manage(git_watch::WorktreeWatcher::default());

            // Vertically centre the macOS traffic lights in our 46px top bar so
            // they line up with the chrome icons (the `trafficLightPosition`
            // config field is ignored under titleBarStyle: Overlay). decorum
            // does it natively and re-applies on resize.
            #[cfg(target_os = "macos")]
            {
                use tauri_plugin_decorum::WebviewWindowExt;
                if let Some(main) = app.get_webview_window("main") {
                    // decorum centers the buttons at `y/2 + 4 + button_height/2`
                    // from the window top. The chrome icons sit at the 46px bar's
                    // center (~23px), so y=22 lines the traffic lights up with them.
                    let _ = main.set_traffic_lights_inset(19.0, 22.0);
                }
            }

            log::info!("santree started");
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|app, event| {
            // Kill every terminal child on exit so nothing is leaked.
            if let tauri::RunEvent::ExitRequested { .. } = event {
                if let Some(pty) = app.try_state::<santree_pty::PtyManager>() {
                    pty.close_all();
                }
            }
        });
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates `src/bindings.ts`. Run on its own via `pnpm gen:bindings`,
    /// and also guards that the command set always produces valid bindings.
    #[test]
    fn export_bindings_succeeds() {
        export_bindings(&specta_builder()).expect("bindings export should succeed");
    }

    #[test]
    fn merge_paths_prepends_login_and_dedups() {
        // Login PATH wins ordering; current-only entries are appended; dupes dropped.
        let login = "/opt/homebrew/bin:/usr/bin:/bin";
        let current = "/usr/bin:/bin:/sbin";
        assert_eq!(
            merge_paths(login, current),
            "/opt/homebrew/bin:/usr/bin:/bin:/sbin"
        );
    }

    #[test]
    fn merge_paths_is_noop_when_login_covers_current() {
        let path = "/opt/homebrew/bin:/usr/bin:/bin";
        assert_eq!(merge_paths(path, path), path);
    }

    #[test]
    fn merge_paths_skips_empty_segments() {
        assert_eq!(merge_paths("/usr/bin::", ":/bin:"), "/usr/bin:/bin");
    }
}
