//! Tauri application wiring: logging, the typed command bridge, and the builder.
//!
//! Keep this file about *registration* only. Command bodies live in
//! [`commands`], and the real logic lives in the `santree-core` crate.

mod commands;
mod db;
mod linear;
mod repo;
mod settings;
mod terminal;

use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

/// The app's concrete `tauri-specta` builder type (Tauri's default `Wry` runtime).
type AppBuilder = Builder<tauri::Wry>;

/// Where the generated TypeScript client is written, relative to `src-tauri`
/// (the cwd for both `tauri dev` and `cargo test`).
const BINDINGS_PATH: &str = "../src/bindings.ts";

/// Build the `tauri-specta` command bridge.
///
/// Centralised so the binary (`run`), the debug export, and the `gen:bindings`
/// test all use the exact same command set — there's no way for them to drift.
fn specta_builder() -> AppBuilder {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::list_repos,
        commands::add_repo,
        commands::list_agents,
        commands::agent_auth,
        commands::list_tasks,
        commands::list_worktrees,
        commands::worktree_diff,
        commands::worktree_terminal,
        commands::commit_suggestion,
        commands::file_tree,
        commands::stage_meta,
        commands::list_triage_tickets,
        commands::triage_detail,
        commands::triage_set_state,
        commands::triage_schedule,
        commands::triage_thread,
        commands::triage_ask,
        commands::get_settings,
        commands::list_claude_commands,
        commands::get_setting,
        commands::set_setting,
        commands::resolve_setting,
        commands::linear_auth_status,
        commands::linear_orgs,
        commands::set_repo_linear_org,
        commands::linear_list_issues,
        commands::linear_connect,
        terminal::terminal_open,
        terminal::terminal_write,
        terminal::terminal_resize,
        terminal::terminal_close,
    ])
}

/// Write `src/bindings.ts` from the current command set.
///
/// Called from `run()` in debug builds and from the `export_bindings` test
/// (which is what `pnpm gen:bindings` drives).
#[cfg(debug_assertions)]
fn export_bindings(builder: &AppBuilder) -> anyhow::Result<()> {
    builder.export(
        specta_typescript::Typescript::default()
            .header("// @generated by tauri-specta. Do not edit by hand.\n"),
        BINDINGS_PATH,
    )?;
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Logging. Honour `RUST_LOG` if set, otherwise default to `info`.
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .init();

    let builder = specta_builder();

    // In debug builds, (re)generate `src/bindings.ts` on every run so the typed
    // client tracks the Rust commands during development. Release builds skip
    // this — the committed bindings are used as-is.
    #[cfg(debug_assertions)]
    export_bindings(&builder).expect("failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_decorum::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            // Wire specta-registered events into the app (none yet, but this is
            // where they'd attach as the app grows).
            builder.mount_events(app);

            // Open the app database and make the pool available to commands.
            let data_dir = app.path().app_data_dir().expect("resolving app data dir");
            let db = tauri::async_runtime::block_on(db::init(data_dir.join("santree.db")))
                .expect("initializing database");
            app.manage(db);

            // Owns all live terminal sessions; commands read it from state.
            app.manage(santree_pty::PtyManager::new());

            // Vertically centre the macOS traffic lights in our 46px top bar so
            // they line up with the chrome icons (the `trafficLightPosition`
            // config field is ignored under titleBarStyle: Overlay). decorum
            // does it natively and re-applies on resize.
            #[cfg(target_os = "macos")]
            {
                use tauri_plugin_decorum::WebviewWindowExt;
                if let Some(main) = app.get_webview_window("main") {
                    // decorum centers the buttons at `y/2 + 4 + button_height/2`
                    // from the window top. The chrome icons sit at the 46px bar's
                    // center (~23px), so y=22 lines the traffic lights up with them.
                    let _ = main.set_traffic_lights_inset(19.0, 22.0);
                }
            }

            tracing::info!("santree started");
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|app, event| {
            // Kill every terminal child on exit so nothing is leaked.
            if let tauri::RunEvent::ExitRequested { .. } = event {
                if let Some(pty) = app.try_state::<santree_pty::PtyManager>() {
                    pty.close_all();
                }
            }
        });
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates `src/bindings.ts`. Run on its own via `pnpm gen:bindings`,
    /// and also guards that the command set always produces valid bindings.
    #[test]
    fn export_bindings_succeeds() {
        export_bindings(&specta_builder()).expect("bindings export should succeed");
    }
}
