// @generated by tauri-specta. Do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Connected repositories. */
	listRepos: () => typedError<Repo[], string>(__TAURI_INVOKE("list_repos")),
	/**  Add a repository from a local folder, validating it is a git work tree. */
	addRepo: (path: string) => typedError<Repo, string>(__TAURI_INVOKE("add_repo", { path })),
	/**  Available coding agents and their models. */
	listAgents: () => __TAURI_INVOKE<AgentDef[]>("list_agents"),
	/**
	 *  An agent harness's authentication / subscription status. Live for Claude
	 *  (read from `~/.claude.json`), placeholders for the work-in-progress harnesses.
	 */
	agentAuth: (kind: AgentKind) => __TAURI_INVOKE<AgentAuth>("agent_auth", { kind }),
	/**  All tickets, positioned for the dependency graph. */
	listTasks: () => __TAURI_INVOKE<Task[]>("list_tasks"),
	/**  Active agent worktrees. */
	listWorktrees: () => __TAURI_INVOKE<Worktree[]>("list_worktrees"),
	/**  The working-tree diff for a worktree. */
	worktreeDiff: (worktreeId: string) => __TAURI_INVOKE<WorktreeDiff>("worktree_diff", { worktreeId }),
	/**  A worktree's seed terminal transcript and status. */
	worktreeTerminal: (worktreeId: string) => __TAURI_INVOKE<Terminal>("worktree_terminal", { worktreeId }),
	/**  A seed commit message suggestion for a worktree. */
	commitSuggestion: (worktreeId: string) => __TAURI_INVOKE<string>("commit_suggestion", { worktreeId }),
	/**  The worktree file browser tree. */
	fileTree: () => __TAURI_INVOKE<FileEntry[]>("file_tree"),
	/**  Stages an agent run progresses through (for session progress UI). */
	stageMeta: () => __TAURI_INVOKE<Stage[]>("stage_meta"),
	/**  Tickets awaiting triage — live from Linear when connected, else the sample set. */
	listTriageTickets: (repo: string) => typedError<TriageTicket[], string>(__TAURI_INVOKE("list_triage_tickets", { repo })),
	/**  The full triage issue (description + comments) for the discussion pane. */
	triageDetail: (repo: string, ticketId: string) => typedError<TriageDetail, string>(__TAURI_INVOKE("triage_detail", { repo, ticketId })),
	/**
	 *  Move a triage issue to a different workflow state (the status picker). Moving
	 *  it out of `triage` is how the UI promotes an item. Requires a connected,
	 *  write-scoped Linear org; a no-op error is returned in mock mode.
	 */
	triageSetState: (repo: string, ticketId: string, stateId: string) => typedError<null, string>(__TAURI_INVOKE("triage_set_state", { repo, ticketId, stateId })),
	/**
	 *  The team triage rotations (who is on-call now), from Linear's responsibility
	 *  schedules — one per team the viewer is on. Empty when none are configured.
	 */
	triageSchedule: (repo: string) => typedError<TriageSchedule[], string>(__TAURI_INVOKE("triage_schedule", { repo })),
	/**  The seed investigation thread for a triage ticket. */
	triageThread: (ticketId: string) => __TAURI_INVOKE<TriageMessage[]>("triage_thread", { ticketId }),
	/**  Investigate a free-text triage question; returns the agent's answer. */
	triageAsk: (question: string) => __TAURI_INVOKE<TriageMessage>("triage_ask", { question }),
	/**
	 *  User settings (the frontend owns live edits after seeding). Each agent's
	 *  `exec` is the user's *override* (empty by default); the executable detected on
	 *  PATH is reported separately via [`agent_auth`] and shown as the grayed default.
	 */
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**
	 *  The Claude slash-commands offered by the triage "Investigate" picker. Always
	 *  includes the global `~/.claude/commands`; when a repo name is given, also its
	 *  own `.claude/commands` (so the repo scope can list both).
	 */
	listClaudeCommands: (repo: string | null) => typedError<ClaudeCommands, string>(__TAURI_INVOKE("list_claude_commands", { repo })),
	/**  Read a setting for an exact scope (`"app"` or `"repo:<name>"`). */
	getSetting: (scope: string, key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_setting", { scope, key })),
	/**  Write (or clear, when `value` is null) a setting for a scope. */
	setSetting: (scope: string, key: string, value: string | null) => typedError<null, string>(__TAURI_INVOKE("set_setting", { scope, key, value })),
	/**  Resolve a repo-scoped setting: the repo's override, else the app value. */
	resolveSetting: (repo: string, key: string) => typedError<string | null, string>(__TAURI_INVOKE("resolve_setting", { repo, key })),
	/**  Connection status for a repo: whether any org is connected, and which one it uses. */
	linearAuthStatus: (repo: string) => typedError<LinearStatus, string>(__TAURI_INVOKE("linear_auth_status", { repo })),
	/**  Every connected Linear organization. */
	linearOrgs: () => typedError<LinearOrg[], string>(__TAURI_INVOKE("linear_orgs")),
	/**  Bind (or clear) the Linear org a repo uses. */
	setRepoLinearOrg: (repo: string, slug: string | null) => typedError<null, string>(__TAURI_INVOKE("set_repo_linear_org", { repo, slug })),
	/**  Fetch the repo's assigned Linear issues as a positioned dependency graph. */
	linearListIssues: (repo: string) => typedError<Task[], string>(__TAURI_INVOKE("linear_list_issues", { repo })),
	/**  Run the Linear OAuth flow; returns the updated org list. */
	linearConnect: () => typedError<LinearOrg[], string>(__TAURI_INVOKE("linear_connect")),
	/**  Spawn a process behind a PTY and stream its raw output over `on_output`. */
	terminalOpen: (opts: TerminalOpenOpts, onOutput: Channel<number[]>) => typedError<number, string>(__TAURI_INVOKE("terminal_open", { opts, onOutput })),
	/**  Write raw bytes (keystrokes or a seed) to a session. */
	terminalWrite: (id: number, data: string) => typedError<null, string>(__TAURI_INVOKE("terminal_write", { id, data })),
	/**  Resize a session's PTY to the visible grid. */
	terminalResize: (id: number, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("terminal_resize", { id, cols, rows })),
	/**  Kill a session's child and free it. */
	terminalClose: (id: number) => typedError<null, string>(__TAURI_INVOKE("terminal_close", { id })),
};

/* Types */
/**  What an agent worktree is currently doing. */
export type Activity = "Running" | "Idle" | "Awaiting";

/**
 *  An agent harness's authentication / subscription status, as shown in the
 *  harness settings tab. Mocked today (the CLI owns real auth).
 */
export type AgentAuth = {
	/**  Whether a CLI session is currently authenticated. */
	connected: boolean,
	/**  How auth is established (only "CLI" today; API keys aren't supported yet). */
	method: string,
	/**  Billing provider, e.g. "Anthropic API". */
	provider: string,
	/**  Subscription plan, e.g. "Max". */
	plan: string,
	/**  Organization the account belongs to. */
	org: string,
	/**  Signed-in account label. */
	account: string,
	/**  Where the harness keeps its settings file (for the "Open" affordance). */
	settingsPath: string,
	/**  Shell command that (re)authenticates this harness, e.g. "claude /login". */
	loginCmd: string,
	/**
	 *  The executable found on the user's PATH, shown as the grayed default when
	 *  no custom path is set. Empty when nothing was found.
	 */
	detectedExec: string,
};

/**  A selectable agent and the models it offers in the launch tray. */
export type AgentDef = {
	key: AgentKind,
	label: string,
	short: string,
	models: string[],
};

/**  Which coding agent ("harness") runs a task. */
export type AgentKind = "Claude" | "Codex" | "Cursor" | "Opencode";

/**  Per-agent configuration: which executable and default model to use. */
export type AgentSetting = {
	key: AgentKind,
	exec: string,
	model: string,
};

/**  CI state of a pull request. */
export type CheckState = "Running" | "Passing";

/**
 *  A Claude slash-command discovered on disk under a `.claude/commands` folder.
 *  Invoked as `/<name> <arg>` — the triage "Investigate" picker offers these.
 */
export type ClaudeCommand = {
	/**  Invocation name (the file stem, without `.md`), e.g. `investigate-ticket`. */
	name: string,
	/**  The command's `description:` frontmatter, when present. */
	description: string | null,
};

/**
 *  Claude commands available to the investigate picker, split by where they live
 *  so the repo scope can distinguish its own commands from the global ones.
 */
export type ClaudeCommands = {
	/**  Commands from the user's `~/.claude/commands`. */
	global: ClaudeCommand[],
	/**  Commands from the repo's `.claude/commands` (empty for the app scope). */
	repo: ClaudeCommand[],
};

/**  A code location referenced by a triage answer. */
export type CodeRef = {
	path: string,
};

/**  A changed file within a worktree's diff. */
export type DiffFile = {
	path: string,
	addLines: number,
	delLines: number,
	tag: DiffTag,
	hunks: DiffHunk[],
};

/**  A contiguous block of changes within a file. */
export type DiffHunk = {
	header: string,
	lines: DiffLine[],
};

/**  One line inside a diff hunk. */
export type DiffLine = {
	kind: DiffLineKind,
	text: string,
};

/**  The role of a single diff line. */
export type DiffLineKind = "Add" | "Del" | "Context";

/**  Whether a diffed file is newly added or modified in place. */
export type DiffTag = "New" | "Modified";

/**  An entry in the worktree file browser. */
export type FileEntry = {
	name: string,
	icon: string,
	depth: number,
	dir: boolean,
	modified: boolean,
};

/**  Which trackers/services are connected. */
export type Integrations = {
	linear: boolean,
	triage: boolean,
	github: boolean,
};

/**  A connected Linear organization. */
export type LinearOrg = {
	slug: string,
	name: string,
};

/**  Linear connection status surfaced to the UI for a given repo. */
export type LinearStatus = {
	/**  True when at least one org is connected. */
	authenticated: boolean,
	/**  The slug of the org this repo uses (its own link, or the only/first org). */
	orgSlug: string | null,
	/**  Display name of that org. */
	org: string | null,
};

/**  Who authored a triage message. */
export type MessageRole = "User" | "Agent";

/**  Priority of a triage ticket. */
export type Priority = "Urgent" | "High" | "Medium" | "Low";

/**  A pull request opened from a worktree. */
export type PullRequest = {
	number: number,
	checks: CheckState,
};

/**  A connected repository / task-tracker pairing. */
export type Repo = {
	name: string,
	tracker: string,
	/**  Number of agents currently active on this repo. */
	agents: number,
	/**
	 *  Absolute path on disk, for repos the user added from a local folder.
	 *  `None` for the built-in seed repos.
	 */
	path: string | null,
};

/**  User settings seeded by the backend (the frontend then owns live edits). */
export type Settings = {
	defaultAgent: AgentKind,
	integrations: Integrations,
	agents: AgentSetting[],
};

/**  A stage in an agent run, with its progress percentage. */
export type Stage = {
	label: string,
	pct: number,
};

/**
 *  A ticket in the dependency graph. `x`/`y` are its canvas position; `addLines`
 *  / `delLines` are the projected diff size once worked.
 */
export type Task = {
	id: string,
	title: string,
	project: string,
	status: TaskStatus,
	ready: boolean,
	blockedBy: string[],
	x: number,
	y: number,
	addLines: number,
	delLines: number,
};

/**  Lifecycle status of a ticket / worktree. */
export type TaskStatus = "InReview" | "InProgress" | "Todo" | "Backlog";

/**  A worktree's terminal session: its seed transcript plus status. */
export type Terminal = {
	worktreeId: string,
	lines: TerminalLine[],
	running: boolean,
	awaiting: boolean,
	status: string,
	statusTone: Tone,
	/**  Working directory shown in the header, e.g. `.worktrees/ak-165`. */
	cwd: string,
};

/**  One line of streamed terminal output. */
export type TerminalLine = {
	text: string,
	tone: Tone,
	indent: number,
};

/**
 *  How the frontend asks for a new terminal. An empty `command` means the user's
 *  login shell.
 */
export type TerminalOpenOpts = {
	cwd: string | null,
	command: string,
	args: string[],
	env: { [key in string]: string },
	cols: number,
	rows: number,
};

/**
 *  Semantic color tone for a terminal/diff line. The frontend maps each tone to
 *  a concrete theme color.
 */
export type Tone = "Muted" | "Default" | "Accent" | "Green" | "Cyan" | "Amber" | "Red";

/**  A comment on a triage issue (markdown body), with threaded replies. */
export type TriageComment = {
	author: string,
	/**  Public avatar URL of the author, when they have one. */
	avatarUrl: string | null,
	created: string,
	/**  Markdown — may contain inline images. */
	body: string,
	/**  Threaded replies, in chronological order. */
	children: TriageComment[],
};

/**
 *  The full triage issue as rendered in the discussion pane: the Linear issue's
 *  description, metadata, and comment thread.
 */
export type TriageDetail = {
	id: string,
	title: string,
	priority: Priority,
	/**  Workflow state name (e.g. "Triage"). */
	state: string,
	/**  Id of the current workflow state (for the status picker's selection). */
	stateId: string | null,
	/**  All workflow states the issue can move to, ordered as in Linear. */
	states: WorkflowState[],
	/**  Canonical Linear URL for the issue. */
	url: string,
	author: string,
	/**  Public avatar URL of the issue creator, when they have one. */
	authorAvatarUrl: string | null,
	created: string,
	labels: string[],
	project: string | null,
	sla: string | null,
	snoozedUntil: string | null,
	/**  Markdown description — may contain inline images. */
	description: string,
	comments: TriageComment[],
};

/**  One message in a triage investigation thread. */
export type TriageMessage = {
	role: MessageRole,
	text: string,
	refs: CodeRef[],
};

/**  The team triage rotation surfaced from Linear's triage responsibility. */
export type TriageSchedule = {
	team: string,
	scheduleName: string,
	currentName: string | null,
	/**  True when the signed-in viewer is the one currently on triage. */
	currentIsMe: boolean,
	shifts: TriageShift[],
};

/**  A single on-call slot in a triage rotation. */
export type TriageShift = {
	name: string,
	/**  Human time range, e.g. "Mon–Wed". */
	range: string,
	isCurrent: boolean,
	isMe: boolean,
};

/**  An untriaged ticket awaiting investigation (the queue row). */
export type TriageTicket = {
	id: string,
	title: string,
	priority: Priority,
	age: string,
	meta: string,
	/**
	 *  The team key (e.g. "MSG"), used to group the queue when the viewer is on
	 *  more than one team.
	 */
	team: string | null,
	/**  Human SLA hint (e.g. "SLA in 3h", "SLA breached"), if the issue has one. */
	sla: string | null,
	/**
	 *  When set, the issue is snoozed until this human label; the UI greys it out
	 *  and sinks it to the bottom of the queue.
	 */
	snoozedUntil: string | null,
};

/**
 *  A workflow state an issue can move to (one of its team's states). Moving an
 *  issue out of the `triage` state — e.g. into `backlog`/`unstarted` — is how the
 *  UI "promotes" a triage item.
 */
export type WorkflowState = {
	id: string,
	name: string,
	/**  Linear state category: triage | backlog | unstarted | started | completed | canceled. */
	type: string,
	/**  State color (hex), as configured in Linear. */
	color: string,
};

/**  A live git worktree with an agent attached. */
export type Worktree = {
	id: string,
	title: string,
	status: TaskStatus,
	addLines: number,
	delLines: number,
	dirty: boolean,
	ahead: number,
	agent: AgentKind,
	activity: Activity,
	pr: PullRequest | null,
};

/**
 *  The full diff for a worktree. When `clean`, there is nothing to commit and
 *  `pr_note` describes the open PR instead.
 */
export type WorktreeDiff = {
	clean: boolean,
	files: DiffFile[],
	prNote: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

