// @generated by tauri-specta. Do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Connected repositories. */
	listRepos: () => typedError<Repo[], CmdError>(__TAURI_INVOKE("list_repos")),
	/**  Add a repository from a local folder, validating it is a git work tree. */
	addRepo: (path: string) => typedError<Repo, CmdError>(__TAURI_INVOKE("add_repo", { path })),
	/**  Available coding agents and their models. */
	listAgents: () => __TAURI_INVOKE<AgentDef[]>("list_agents"),
	/**
	 *  Aggregated Claude Code token usage across all local session transcripts
	 *  (`~/.claude/projects/**\/*.jsonl`) — period/model/session totals + context fill.
	 *  Empty when there are no transcripts. Resolves the price table first (a daily
	 *  background refresh from LiteLLM, cached in SQLite, over the static fallback),
	 *  then runs the cold parse on the blocking pool (cached per-file afterwards).
	 */
	claudeUsage: () => typedError<UsageReport, CmdError>(__TAURI_INVOKE("claude_usage")),
	/**
	 *  An agent harness's authentication / subscription status. Live for Claude
	 *  (read from `~/.claude.json`), placeholders for the work-in-progress harnesses.
	 */
	agentAuth: (kind: AgentKind) => __TAURI_INVOKE<AgentAuth>("agent_auth", { kind }),
	/**
	 *  The `gh` CLI integration status for Settings → Integrations: installed?
	 *  authenticated? as which account? Infallible — a missing or signed-out `gh`
	 *  is reported via the status flags rather than as an error, since GitHub can't
	 *  be turned off and the view always renders.
	 */
	githubStatus: () => __TAURI_INVOKE<GithubStatus>("github_status"),
	/**
	 *  The repo's live agent worktrees (DB-tracked, with live git stats). Empty when
	 *  the repo has no local path.
	 */
	worktrees: (repo: string) => typedError<Worktree[], CmdError>(__TAURI_INVOKE("worktrees", { repo })),
	/**
	 *  The repo's base branch as a worktree-like entry (repo root on main/master),
	 *  for the Trees "main" entry. `None` when the repo has no local path.
	 */
	baseWorktree: (repo: string) => typedError<{
	/**  The issue identifier this worktree was created for (e.g. "AK-165"). */
	id: string,
	title: string,
	/**
	 *  The ticket's status, when the issue is one santree knows about. `None`
	 *  when there's nothing to know (the base worktree, or a worktree whose
	 *  issue we can't resolve) — the UI renders no chip rather than a made-up one.
	 */
	status: TaskStatus | null,
	addLines: number,
	delLines: number,
	dirty: boolean,
	/**  Commits this branch is ahead of its base. */
	ahead: number,
	/**  Commits this branch is behind its base (origin/<base>). */
	behind: number,
	/**
	 *  Commits on this branch not yet pushed to its remote (what `git push` would
	 *  upload); 0 when the remote is up to date.
	 */
	unpushed: number,
	/**
	 *  Commits on this branch's remote tracking ref not yet local (what `git pull`
	 *  would download — PR-UI suggestions, "Update branch", a teammate's push);
	 *  0 when local is up to date or the branch has no remote.
	 */
	remoteBehind: number,
	/**
	 *  When `remote_behind > 0`, whether pulling origin/<branch> would conflict
	 *  with local commits (from a virtual merge). Disables the Pull button — a
	 *  conflicting pull can't be applied automatically and must be resolved in the
	 *  worktree. Always false when nothing is pending (`remote_behind == 0`).
	 */
	pullConflict: boolean,
	/**
	 *  The agent attached to this worktree, once one has actually been launched
	 *  in it. `None` for the base worktree (no agent concept) and for worktrees
	 *  with no session yet.
	 */
	agent: AgentKind | null,
	/**
	 *  Derived from the worktree's live agent session. `None` when there is no
	 *  session to derive it from — the backend does not guess.
	 */
	activity: Activity | null,
	/**  Git branch checked out in the worktree (e.g. "feature/ak-165-…"). */
	branch: string,
	/**  Absolute filesystem path of the worktree directory. */
	path: string,
	/**  Linear project the issue belongs to, used to group the Trees tabs. */
	project: string | null,
	/**  Branch this worktree was created from. */
	baseBranch: string,
	/**  Whether `.santree/init.sh` has been run for this worktree. */
	setupRan: boolean,
	/**
	 *  True only for the optimistic frontend placeholder shown while a worktree
	 *  is still being created (it has no branch/path yet). The backend always
	 *  sets this to `false` — the `true` case exists only in the frontend's own
	 *  placeholder object (`AppContext.pendingLaunches`), built in JS and never
	 *  deserialized from this type (`Worktree` only derives `Serialize`).
	 */
	pending: boolean,
} | null, CmdError>(__TAURI_INVOKE("base_worktree", { repo })),
	/**
	 *  Start a task: create a worktree for an issue (branching off `base`) and record
	 *  the issue ↔ worktree link. Running `.santree/init.sh` is a separate step —
	 *  see `run_worktree_setup_streamed` — so it isn't gated on this call.
	 */
	createWorktree: (repo: string, issueId: string, title: string, project: string | null, base: string | null, agent: AgentKind) => typedError<Worktree, CmdError>(__TAURI_INVOKE("create_worktree", { repo, issueId, title, project, base, agent })),
	/**
	 *  Remove a worktree (and its branch), drop the issue link, and delete its
	 *  on-disk work prompt.
	 */
	removeWorktree: (repo: string, issueId: string) => typedError<null, CmdError>(__TAURI_INVOKE("remove_worktree", { repo, issueId })),
	/**
	 *  Run a worktree's setup script, streaming each output line over `on_event` for
	 *  the Trees "Setup" tab; records it as run on success.
	 */
	runWorktreeSetupStreamed: (repo: string, issueId: string, onEvent: Channel<SetupEvent>) => typedError<null, CmdError>(__TAURI_INVOKE("run_worktree_setup_streamed", { repo, issueId, onEvent })),
	/**
	 *  Stop a running setup script (the Setup tab's Stop button). Killing the child
	 *  ends the stream, so the run reports `Done { ok: false }` and the tab closes like
	 *  any other failed setup. Returns whether a run was actually stopped.
	 */
	cancelWorktreeSetup: (repo: string, issueId: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("cancel_worktree_setup", { repo, issueId })),
	/**
	 *  Merge the base branch into the worktree (the "pull from main/master" button).
	 *  Errors on a conflicting merge; returns the base ref that was merged on success.
	 */
	pullWorktree: (repo: string, issueId: string) => typedError<string, CmdError>(__TAURI_INVOKE("pull_worktree", { repo, issueId })),
	/**
	 *  Push the worktree's branch to origin (the Trees "Push" button / post-commit
	 *  auto-push). Network op — may fail (no auth, rejected non-fast-forward, …).
	 */
	pushWorktree: (repo: string, issueId: string) => typedError<null, CmdError>(__TAURI_INVOKE("push_worktree", { repo, issueId })),
	/**
	 *  Integrate origin/<branch> into the worktree's own branch — the Trees "Pull"
	 *  button, for commits added to the branch remotely (PR-UI suggestions, "Update
	 *  branch", a teammate's push). Fast-forwards when possible, else merges; refuses
	 *  up front (nothing touched) when the merge would conflict.
	 */
	pullRemoteWorktree: (repo: string, issueId: string) => typedError<null, CmdError>(__TAURI_INVOKE("pull_remote_worktree", { repo, issueId })),
	/**
	 *  Fast-forward the repo's local base branch (main/master) to origin — the
	 *  "update master" action. Returns the base branch that was updated.
	 */
	updateBaseBranch: (repo: string, issueId: string) => typedError<string, CmdError>(__TAURI_INVOKE("update_base_branch", { repo, issueId })),
	/**  The worktree's working-tree status (changed files) for the commit box. */
	worktreeStatus: (repo: string, issueId: string) => typedError<ChangedFile[], CmdError>(__TAURI_INVOKE("worktree_status", { repo, issueId })),
	/**  A unified diff for one changed file (staged + unstaged vs HEAD). */
	worktreeFileDiff: (repo: string, issueId: string, path: string, untracked: boolean) => typedError<string, CmdError>(__TAURI_INVOKE("worktree_file_diff", { repo, issueId, path, untracked })),
	/**  The old/new full file contents, for the diff viewer's context expansion. */
	worktreeFileSource: (repo: string, issueId: string, path: string) => typedError<FileSource, CmdError>(__TAURI_INVOKE("worktree_file_source", { repo, issueId, path })),
	/**  Every browsable file in the worktree (tracked + untracked, gitignore-aware). */
	worktreeFiles: (repo: string, issueId: string) => typedError<string[], CmdError>(__TAURI_INVOKE("worktree_files", { repo, issueId })),
	/**
	 *  Start (or re-point) the filesystem watcher at the given repo's worktrees, so
	 *  the Trees views refresh live when files change on disk (e.g. an agent editing
	 *  in the terminal). A no-op for repos without a local path; idempotent, so the
	 *  frontend can call it on every Trees mount / repo change.
	 */
	watchWorktrees: (repo: string) => typedError<null, CmdError>(__TAURI_INVOKE("watch_worktrees", { repo })),
	/**  Stage a single file. */
	stagePath: (repo: string, issueId: string, path: string) => typedError<null, CmdError>(__TAURI_INVOKE("stage_path", { repo, issueId, path })),
	/**  Unstage a single file. */
	unstagePath: (repo: string, issueId: string, path: string) => typedError<null, CmdError>(__TAURI_INVOKE("unstage_path", { repo, issueId, path })),
	/**  Discard a file's uncommitted changes (delete if untracked, else restore HEAD). */
	discardPath: (repo: string, issueId: string, path: string, untracked: boolean) => typedError<null, CmdError>(__TAURI_INVOKE("discard_path", { repo, issueId, path, untracked })),
	/**  Stage every change in the worktree. */
	stageAllPaths: (repo: string, issueId: string) => typedError<null, CmdError>(__TAURI_INVOKE("stage_all_paths", { repo, issueId })),
	/**  Unstage everything in the worktree. */
	unstageAllPaths: (repo: string, issueId: string) => typedError<null, CmdError>(__TAURI_INVOKE("unstage_all_paths", { repo, issueId })),
	/**  Commit the worktree (optionally staging everything first). */
	commitWorktree: (repo: string, issueId: string, message: string, stageAll: boolean) => typedError<null, CmdError>(__TAURI_INVOKE("commit_worktree", { repo, issueId, message, stageAll })),
	/**  Draft a commit message from the staged diff via a headless `claude -p` call. */
	commitMessage: (repo: string, issueId: string) => typedError<string, CmdError>(__TAURI_INVOKE("commit_message", { repo, issueId })),
	/**
	 *  The saved commit-message draft for a worktree, or `None`. Survives tab
	 *  switches / restarts until the worktree commits (which clears it).
	 */
	commitDraft: (repo: string, issueId: string) => typedError<string | null, CmdError>(__TAURI_INVOKE("commit_draft", { repo, issueId })),
	/**  Save (or clear, when blank) a worktree's commit-message draft. */
	setCommitDraft: (repo: string, issueId: string, message: string) => typedError<null, CmdError>(__TAURI_INVOKE("set_commit_draft", { repo, issueId, message })),
	/**
	 *  Refresh a worktree's stored Linear title (the Issue tab calls this when the
	 *  live title differs, keeping the sidebar accurate without the list hitting Linear).
	 */
	setWorktreeTitle: (repo: string, issueId: string, title: string) => typedError<null, CmdError>(__TAURI_INVOKE("set_worktree_title", { repo, issueId, title })),
	/**
	 *  Render the agent's opening prompt for a freshly-started worktree (the `work`
	 *  template, from live ticket data), write it to a stable on-disk file, and
	 *  return that file's **path** — not the text. The terminal seeds
	 *  `exec <agent> 'Read <path> and follow the instructions inside.'`, so a long
	 *  prompt can't overflow the interactive-shell line or be mangled by the PTY line
	 *  editor. Regenerated on every launch (re-fetches the live ticket), so it always
	 *  reflects the latest Linear state; deleted with the worktree.
	 */
	workPrompt: (repo: string, issueId: string) => typedError<string, CmdError>(__TAURI_INVOKE("work_prompt", { repo, issueId })),
	/**
	 *  Render the Triage-investigation opening prompt for a ticket (the `triage`
	 *  template around the live ticket), extract its screenshots to files the agent
	 *  can `Read`, write the prompt to a stable on-disk file, and return that file's
	 *  **path** — the terminal seeds `exec <agent> 'Read <path> …'` with it. The
	 *  investigation analog of [`work_prompt`]; regenerated on every launch.
	 */
	investigatePrompt: (repo: string, issueId: string) => typedError<string, CmdError>(__TAURI_INVOKE("investigate_prompt", { repo, issueId })),
	/**
	 *  Render the CI-fix opening prompt (the failing check `log` + guardrails) to a
	 *  per-worktree file and return its **path** — the "Fix CI" terminal seeds
	 *  `exec <agent> 'Read <path> …'` with it (the log is too large to type into the
	 *  PTY). Rewritten each launch so it reflects the latest failing run.
	 */
	fixCiPrompt: (repo: string, issueId: string, log: string) => typedError<string, CmdError>(__TAURI_INVOKE("fix_ci_prompt", { repo, issueId, log })),
	/**
	 *  Find-or-create a worktree for a pull request: reuse the one already tracked
	 *  under `issue_id` if present, else create one that **checks out the PR's head
	 *  branch** (`branch`) so commits made in it land on the PR. Used by the Reviews
	 *  "Fix CI with AI" flow. `base` is the PR's base branch (for the worktree's diff).
	 */
	createWorktreeForPr: (repo: string, issueId: string, title: string, branch: string, base: string | null, agent: AgentKind) => typedError<Worktree, CmdError>(__TAURI_INVOKE("create_worktree_for_pr", { repo, issueId, title, branch, base, agent })),
	/**
	 *  Decide how a terminal that auto-launches `claude` should (re)launch it: resume
	 *  a still-on-disk session, start fresh with a reserved id, or a plain shell.
	 *  `term_key` is the logical terminal id (e.g. `tree:AK-1`, `triage:AK-1`); `cwd`
	 *  is where claude runs. `allow_fresh` mints a new session when none is resumable
	 *  (set on an explicit launch; false on a passive reopen).
	 */
	agentSession: (repo: string, termKey: string, cwd: string, allowFresh: boolean) => typedError<AgentSession, CmdError>(__TAURI_INVOKE("agent_session", { repo, termKey, cwd, allowFresh })),
	/**
	 *  Ticket ids of triage investigations that have a stored (resumable) session —
	 *  i.e. an investigation was started for them at some point. Drives the Triage
	 *  view's tab + resume affordance for past investigations (across app restarts).
	 */
	startedInvestigations: (repo: string) => typedError<string[], CmdError>(__TAURI_INVOKE("started_investigations", { repo })),
	/**
	 *  All persisted extra tabs (Claude / terminal) for the repo's worktrees, in
	 *  open order — loaded on Trees mount so tabs survive app restarts.
	 */
	listWorktreeTabs: (repo: string) => typedError<WorktreeTab[], CmdError>(__TAURI_INVOKE("list_worktree_tabs", { repo })),
	/**
	 *  Persist a new extra tab. The frontend mints `id` (a UUID) so it can patch
	 *  its cache and focus the tab without waiting on the round-trip.
	 */
	addWorktreeTab: (repo: string, worktreeId: string, id: string, kind: TabKind, title: string) => typedError<null, CmdError>(__TAURI_INVOKE("add_worktree_tab", { repo, worktreeId, id, kind, title })),
	/**  Rename an extra tab (blank titles are rejected). */
	renameWorktreeTab: (repo: string, id: string, title: string) => typedError<null, CmdError>(__TAURI_INVOKE("rename_worktree_tab", { repo, id, title })),
	/**  Remove an extra tab; a Claude tab's stored session is forgotten with it. */
	removeWorktreeTab: (repo: string, id: string) => typedError<null, CmdError>(__TAURI_INVOKE("remove_worktree_tab", { repo, id })),
	/**
	 *  Draft a PR title + body for the create-PR dialog. With `fill`, the body is
	 *  AI-generated from the repo's PR template + the branch diff; otherwise it's the
	 *  raw template. Title defaults to the first commit's subject.
	 */
	prDraft: (repo: string, issueId: string, fill: boolean) => typedError<PrDraft, CmdError>(__TAURI_INVOKE("pr_draft", { repo, issueId, fill })),
	/**
	 *  Push the worktree branch and open a pull request via the GitHub API (optionally
	 *  as a draft, requesting `reviewers` by login). Returns the new PR's number and
	 *  URL (the frontend opens it in the browser).
	 */
	createPullRequest: (repo: string, issueId: string, title: string, body: string, draft: boolean, reviewers: string[]) => typedError<NewPr, CmdError>(__TAURI_INVOKE("create_pull_request", { repo, issueId, title, body, draft, reviewers })),
	/**
	 *  Candidate reviewers (repo collaborators) for the create-PR dialog's picker.
	 *  Empty when GitHub isn't connected.
	 */
	prReviewers: (repo: string, issueId: string) => typedError<Reviewer[], CmdError>(__TAURI_INVOKE("pr_reviewers", { repo, issueId })),
	/**
	 *  Live PR status (number, URL, merge state) for each tracked worktree, from
	 *  GitHub. Empty when `gh` isn't authenticated; worktrees without a PR are omitted.
	 */
	worktreePrs: (repo: string) => typedError<WorktreePr[], CmdError>(__TAURI_INVOKE("worktree_prs", { repo })),
	/**
	 *  The Reviews dashboard inbox for the org the active `repo` belongs to: the
	 *  viewer's open PRs, PRs individually requesting their review, and one section
	 *  per team that has open requests. Empty when `gh` isn't authenticated.
	 */
	reviews: (repo: string) => typedError<ReviewInbox, CmdError>(__TAURI_INVOKE("reviews", { repo })),
	/**
	 *  The merge queue for the active `repo`'s default branch — the ordered list of
	 *  PRs waiting to merge, so the user can see where their own PRs sit. `None` when
	 *  `gh` isn't authenticated or the repo has no merge queue enabled.
	 */
	mergeQueue: (repo: string) => typedError<{
	/**  "owner/name" of the repo whose queue this is. */
	repo: string,
	/**  The branch the queue merges into (its default branch). */
	branch: string,
	entries: MergeQueueEntry[],
} | null, CmdError>(__TAURI_INVOKE("merge_queue", { repo })),
	/**
	 *  Full detail for one PR — body, conversation (comments + reviews + inline
	 *  threads), and changed files with diffs. Empty when `gh` isn't authenticated.
	 */
	prDetail: (owner: string, name: string, number: number) => typedError<PrDetail, CmdError>(__TAURI_INVOKE("pr_detail", { owner, name, number })),
	/**
	 *  The repo's full label palette — the options offered by the PR label picker.
	 *  Empty when `gh` isn't authenticated.
	 */
	prRepoLabels: (owner: string, name: string) => typedError<PrLabel[], CmdError>(__TAURI_INVOKE("pr_repo_labels", { owner, name })),
	/**
	 *  Replace a PR's labels with exactly `labels` (GitHub PUT semantics — the set is
	 *  overwritten, so an empty list clears them), returning the resulting labels.
	 */
	setPrLabels: (owner: string, name: string, number: number, labels: string[]) => typedError<PrLabel[], CmdError>(__TAURI_INVOKE("set_pr_labels", { owner, name, number, labels })),
	/**
	 *  The raw job log for a failed GitHub Actions check, fetched on demand when the
	 *  user expands the check — sliced to the failing step and classified so the UI
	 *  can tint errors/warnings and collapse the quiet runs between them. `job_id`
	 *  comes from [`PrCheck::job_id`]; empty when `gh` isn't authenticated.
	 * 
	 *  `job_id` crosses the bridge as `f64` because that's what a JS number *is* —
	 *  specta has no 64-bit integer that TypeScript can represent losslessly. GitHub job
	 *  ids are far below 2^53, so the cast back is exact; anything that isn't a
	 *  non-negative whole number never came from a real `PrCheck` and is rejected rather
	 *  than silently truncated by `as`.
	 */
	prCheckLog: (owner: string, name: string, jobId: number | null) => typedError<CheckLog, CmdError>(__TAURI_INVOKE("pr_check_log", { owner, name, jobId })),
	/**
	 *  The old (base) + new (head) full contents of one PR file, fetched on demand so
	 *  the diff can expand unchanged context beyond the patch hunks (GitHub-style).
	 *  `base`/`head` are the commit OIDs from [`PrDetail`]. Empty when GitHub isn't
	 *  connected or the file doesn't exist on that side (added/deleted).
	 */
	prFileSource: (owner: string, name: string, base: string, head: string, path: string) => typedError<FileSource, CmdError>(__TAURI_INVOKE("pr_file_source", { owner, name, base, head, path })),
	/**
	 *  The files a user has marked "Viewed" for a PR, each with the blob SHA it was
	 *  marked at. The frontend keeps a mark only while the file's current head SHA
	 *  still matches (a new commit changing the file drops the mark automatically).
	 */
	reviewedFiles: (prRepo: string, prNumber: number) => typedError<ReviewedFile[], CmdError>(__TAURI_INVOKE("reviewed_files", { prRepo, prNumber })),
	/**  Mark a PR file reviewed (persisting its current blob `sha`) or clear the mark. */
	setFileReviewed: (prRepo: string, prNumber: number, path: string, sha: string, reviewed: boolean) => typedError<null, CmdError>(__TAURI_INVOKE("set_file_reviewed", { prRepo, prNumber, path, sha, reviewed })),
	/**  The repo's `.santree/init.sh` setup script (for the Settings editor). */
	worktreeInitScript: (repo: string) => typedError<ScriptInfo, CmdError>(__TAURI_INVOKE("worktree_init_script", { repo })),
	/**  Write the repo's `.santree/init.sh` setup script. */
	setWorktreeInitScript: (repo: string, content: string) => typedError<null, CmdError>(__TAURI_INVOKE("set_worktree_init_script", { repo, content })),
	/**  Mark `.santree/init.sh` executable so it runs on worktree creation. */
	makeInitScriptExecutable: (repo: string) => typedError<null, CmdError>(__TAURI_INVOKE("make_init_script_executable", { repo })),
	/**
	 *  The "open in app" targets (Finder, editors, terminals) for a worktree.
	 *  Detection shells out (`open -Ra` per candidate), so it runs on the blocking
	 *  pool rather than freezing the UI thread; the result is memoised.
	 */
	listOpeners: () => __TAURI_INVOKE<Opener[]>("list_openers"),
	/**
	 *  Open a path in the chosen app (by opener key). Launching shells out and waits
	 *  on the child, so it runs on the blocking pool rather than the UI thread.
	 */
	openInApp: (path: string, opener: string) => typedError<null, CmdError>(__TAURI_INVOKE("open_in_app", { path, opener })),
	/**  Tickets awaiting triage — live from Linear when connected, else empty. */
	listTriageTickets: (repo: string) => typedError<TriageTicket[], CmdError>(__TAURI_INVOKE("list_triage_tickets", { repo })),
	/**
	 *  The full triage issue (description + comments) for the discussion pane. `None`
	 *  means no Linear org is connected — an issue that genuinely doesn't exist errors
	 *  out of `linear::triage_detail` itself, so reporting this as "not found" would
	 *  have misdescribed exactly the failure the user needs to diagnose.
	 */
	triageDetail: (repo: string, ticketId: string) => typedError<TriageDetail, CmdError>(__TAURI_INVOKE("triage_detail", { repo, ticketId })),
	/**
	 *  Move a triage issue to a different workflow state (the status picker). Moving
	 *  it out of `triage` is how the UI promotes an item. Requires a connected,
	 *  write-scoped Linear org; errors when no org is connected.
	 */
	triageSetState: (repo: string, ticketId: string, stateId: string) => typedError<null, CmdError>(__TAURI_INVOKE("triage_set_state", { repo, ticketId, stateId })),
	/**
	 *  Post a comment on an issue — a top-level comment, or a reply when `parent_id`
	 *  is the id of the comment being replied to. `ticket_id`/`parent_id` are used
	 *  only as GraphQL variables (never as a path or git arg). Requires a
	 *  write-scoped Linear org.
	 */
	triageAddComment: (repo: string, ticketId: string, parentId: string | null, body: string) => typedError<null, CmdError>(__TAURI_INVOKE("triage_add_comment", { repo, ticketId, parentId, body })),
	/**
	 *  Path to the settings file santree passes as `claude --settings <path>`,
	 *  carrying the session-state hooks and santree's own `statusLine` (which prints
	 *  the context-fill bar and captures live usage into the db). Both are always
	 *  present — capture is unconditional; whether the app *displays* the inline
	 *  usage bar is a runtime frontend decision. `None` when the hook binary/db can't
	 *  be resolved — the frontend then launches without the flag. The content is
	 *  setting-independent, so the frontend caches the path forever.
	 */
	claudeHookSettings: () => __TAURI_INVOKE<string | null>("claude_hook_settings"),
	/**
	 *  Like [`claude_hook_settings`] but with a `permissions.deny` block forbidding
	 *  git commit/push — the `--settings` file the "Fix CI" session launches with, so
	 *  the AI fixes + validates but never commits or pushes (the user does that from
	 *  Trees). `None` when the hook binary/db can't be resolved.
	 */
	claudeHookSettingsNoGit: () => __TAURI_INVOKE<string | null>("claude_hook_settings_no_git"),
	/**
	 *  The current state of every Claude session santree has launched, as recorded
	 *  live by the injected hooks. Most-recently-updated first.
	 */
	sessionStates: () => typedError<SessionState[], CmdError>(__TAURI_INVOKE("session_states")),
	/**
	 *  Every santree-launched session's live token/context usage, captured from the
	 *  status-line stdin. Newest first.
	 */
	sessionUsageLive: () => typedError<SessionUsageLive[], CmdError>(__TAURI_INVOKE("session_usage_live")),
	/**
	 *  The team triage rotations (who is on-call now), from Linear's responsibility
	 *  schedules — one per team the viewer is on. Empty when none are configured.
	 */
	triageSchedule: (repo: string) => typedError<TriageSchedule[], CmdError>(__TAURI_INVOKE("triage_schedule", { repo })),
	/**
	 *  User settings, persisted in the database (seeded from defaults on first run).
	 *  Each agent's `exec` is the user's *override* (empty by default); the executable
	 *  detected on PATH is reported separately via [`agent_auth`] and shown as the
	 *  grayed default.
	 */
	getSettings: () => typedError<Settings, CmdError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Persist the full settings blob. The frontend applies edits optimistically and
	 *  calls this to make them durable across restarts.
	 */
	setSettings: (settings: Settings) => typedError<null, CmdError>(__TAURI_INVOKE("set_settings", { settings })),
	/**
	 *  Exit the app. Called from the quit-confirmation dialog once the user confirms a
	 *  ⌘Q / menu quit. By the time this runs the quit is already confirmed, so the
	 *  run-loop's `ExitRequested` handler doesn't gate on anything — it just reaps the
	 *  terminal children (see `run` in lib.rs).
	 */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	/**
	 *  The user's local note for a task — extra context stored only on this machine
	 *  (never synced to Linear). `None` when the task has no note.
	 */
	taskNote: (repo: string, taskId: string) => typedError<string | null, CmdError>(__TAURI_INVOKE("task_note", { repo, taskId })),
	/**  Save (or clear, when blank) the user's local note for a task. */
	setTaskNote: (repo: string, taskId: string, body: string) => typedError<null, CmdError>(__TAURI_INVOKE("set_task_note", { repo, taskId, body })),
	/**
	 *  The current Claude models to suggest in the model pickers — derived live from
	 *  the fetched LiteLLM catalog (cached in SQLite, daily refresh, static fallback),
	 *  so it tracks Anthropic's releases instead of a hardcoded/stale list and includes
	 *  the latest of each family (Opus/Sonnet/Haiku/Fable). See
	 *  [`pricing::claude_models`].
	 */
	claudeModels: () => typedError<string[], CmdError>(__TAURI_INVOKE("claude_models")),
	/**  Read a setting for an exact scope (`"app"` or `"repo:<name>"`). */
	getSetting: (scope: string, key: string) => typedError<string | null, CmdError>(__TAURI_INVOKE("get_setting", { scope, key })),
	/**  Write (or clear, when `value` is null) a setting for a scope. */
	setSetting: (scope: string, key: string, value: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("set_setting", { scope, key, value })),
	/**  Resolve a repo-scoped setting: the repo's override, else the app value. */
	resolveSetting: (repo: string, key: string) => typedError<string | null, CmdError>(__TAURI_INVOKE("resolve_setting", { repo, key })),
	/**
	 *  Every editable AI prompt with its default, the override stored at `scope`
	 *  (`"app"` / `"repo:<name>"`), and its variable/include catalog — for the
	 *  Settings → Prompts editor.
	 */
	listPrompts: (scope: string) => typedError<PromptInfo[], CmdError>(__TAURI_INVOKE("list_prompts", { scope })),
	/**
	 *  Store (or clear, when `content` is null) a prompt's override for `scope`.
	 *  Rejects a non-empty override that doesn't compile, so a broken template can
	 *  never be persisted or reach a real flow.
	 */
	setPrompt: (scope: string, name: string, content: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("set_prompt", { scope, name, content })),
	/**
	 *  Render a *draft* prompt for the live editor preview. With a `detail` (the issue
	 *  the editor already holds in cache) it renders against that real ticket;
	 *  otherwise a built-in sample. Rendering is pure — no fetch — so the editor can
	 *  re-render on every keystroke. Compile/render errors come back in
	 *  `PromptPreview.error`, not as a failure, so the editor can show them inline.
	 */
	previewPrompt: (name: string, content: string, repo: string | null, detail: {
	id: string,
	title: string,
	priority: Priority,
	/**  Workflow state name (e.g. "Triage"). */
	state: string,
	/**  Id of the current workflow state (for the status picker's selection). */
	stateId: string | null,
	/**  All workflow states the issue can move to, ordered as in Linear. */
	states: WorkflowState[],
	/**  Canonical Linear URL for the issue. */
	url: string,
	author: string,
	/**  Public avatar URL of the issue creator, when they have one. */
	authorAvatarUrl: string | null,
	/**  Epoch ms the issue was created — raw, formatted live by the frontend. */
	createdAtMs: number | null,
	labels: string[],
	project: string | null,
	/**  Absolute epoch ms the issue's SLA breaches, if it has one. */
	slaBreachMs: number | null,
	/**  Epoch ms the issue is snoozed until, if snoozed. */
	snoozedUntilMs: number | null,
	/**  Markdown description — may contain inline images. */
	description: string,
	comments: TriageComment[],
} | null) => typedError<PromptPreview, CmdError>(__TAURI_INVOKE("preview_prompt", { name, content, repo, detail })),
	/**
	 *  Create a user-defined shared block (a reusable partial any prompt can
	 *  `{% include %}`). Validates the name and seeds a starter body.
	 */
	createPromptBlock: (name: string, label: string) => typedError<null, CmdError>(__TAURI_INVOKE("create_prompt_block", { name, label })),
	/**  Delete a user-defined shared block, clearing its content across every scope. */
	deletePromptBlock: (name: string) => typedError<null, CmdError>(__TAURI_INVOKE("delete_prompt_block", { name })),
	/**
	 *  The variable names a user-referenced `.env` file defines, for the Environment
	 *  settings' "N variables loaded" readout. Empty when the file is unreadable.
	 * 
	 *  `path` is an arbitrary string from the webview, not a fact — trusting it made
	 *  this a "does this file exist, and what keys does it define?" oracle for *any*
	 *  path on the machine (`~/.aws/credentials`, `.ssh/config`, …). Its real domain
	 *  is the files the user added to Settings → Environment, which santree already
	 *  parses on every spawn, so that list is the allowlist: anything else reads as
	 *  empty. (`env::parse_env_file` separately refuses non-regular files, so neither
	 *  this nor a spawn can be parked on a fifo.)
	 *  Takes the pool off the `AppHandle` rather than as a `State<'_, Db>` argument:
	 *  an async command that borrows state must return a `Result`, and this one's
	 *  contract (a plain `string[]`, empty when there's nothing to show) is worth
	 *  keeping — an unreadable env file isn't an error the UI should toast.
	 */
	envFileVars: (path: string) => __TAURI_INVOKE<string[]>("env_file_vars", { path }),
	/**  Connection status for a repo: whether any org is connected, and which one it uses. */
	linearAuthStatus: (repo: string) => typedError<LinearStatus, CmdError>(__TAURI_INVOKE("linear_auth_status", { repo })),
	/**  Every connected Linear organization. */
	linearOrgs: () => typedError<LinearOrg[], CmdError>(__TAURI_INVOKE("linear_orgs")),
	/**  Bind (or clear) the Linear org a repo uses. */
	setRepoLinearOrg: (repo: string, slug: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("set_repo_linear_org", { repo, slug })),
	/**
	 *  The repo's assigned Linear issues as a positioned dependency graph — live when
	 *  an org is connected, else empty.
	 */
	linearListIssues: (repo: string) => typedError<Task[], CmdError>(__TAURI_INVOKE("linear_list_issues", { repo })),
	/**  Run the Linear OAuth flow; returns the updated org list. */
	linearConnect: () => typedError<LinearOrg[], CmdError>(__TAURI_INVOKE("linear_connect")),
	/**
	 *  Spawn a process behind a PTY and stream its raw output over `on_output`.
	 * 
	 *  The spawn itself is `openpty` + a fork/exec with a full env copy + a reader
	 *  thread — all blocking, and slow enough (an interactive `claude` on a cold
	 *  cache) to stall a tokio worker, so it goes to the blocking pool like
	 *  [`terminal_write`]. Nothing about *what* is spawned or how its bytes stream
	 *  changes: `PtyManager::open` runs exactly once, with the same opts and the
	 *  same verbatim byte-forwarding sink (COMPLIANCE.md).
	 */
	terminalOpen: (opts: TerminalOpenOpts, onOutput: Channel<ArrayBuffer>) => typedError<number, CmdError>(__TAURI_INVOKE("terminal_open", { opts, onOutput })),
	/**
	 *  Write raw bytes (keystrokes or a seed) to a session.
	 * 
	 *  Unlike resize/close, this can genuinely block (see the comment above): the
	 *  write is offloaded to a blocking-pool thread so a stuck child's full PTY
	 *  buffer can never pin a tokio worker and starve every other async command.
	 */
	terminalWrite: (id: number, data: string) => typedError<null, CmdError>(__TAURI_INVOKE("terminal_write", { id, data })),
	/**  Resize a session's PTY to the visible grid. */
	terminalResize: (id: number, cols: number, rows: number) => typedError<null, CmdError>(__TAURI_INVOKE("terminal_resize", { id, cols, rows })),
	/**  Kill a session's child and free it. */
	terminalClose: (id: number) => typedError<null, CmdError>(__TAURI_INVOKE("terminal_close", { id })),
};

/** Events */
export const events = {
	sessionStateChanged: makeEvent<SessionStateChanged>("session-state-changed"),
	sessionUsageChanged: makeEvent<SessionUsageChanged>("session-usage-changed"),
	usageChanged: makeEvent<UsageChanged>("usage-changed"),
	usageProgress: makeEvent<UsageProgress>("usage-progress"),
	worktreeChanged: makeEvent<WorktreeChanged>("worktree-changed"),
};

/* Types */
/**  What an agent worktree is currently doing. */
export type Activity = "Running" | "Idle";

/**
 *  An agent harness's authentication / subscription status, as shown in the
 *  harness settings tab. Read from the agent CLI's own credentials (e.g.
 *  `~/.claude.json`); the CLI owns auth.
 */
export type AgentAuth = {
	/**  Whether a CLI session is currently authenticated. */
	connected: boolean,
	/**  How auth is established (only "CLI" today; API keys aren't supported yet). */
	method: string,
	/**  Billing provider, e.g. "Anthropic API". */
	provider: string,
	/**  Subscription plan, e.g. "Max". */
	plan: string,
	/**  Organization the account belongs to. */
	org: string,
	/**  Signed-in account label. */
	account: string,
	/**  Where the harness keeps its settings file (for the "Open" affordance). */
	settingsPath: string,
	/**  Shell command that (re)authenticates this harness, e.g. "claude /login". */
	loginCmd: string,
	/**
	 *  The executable found on the user's PATH, shown as the grayed default when
	 *  no custom path is set. Empty when nothing was found.
	 */
	detectedExec: string,
};

/**  A selectable agent and the models it offers in the launch tray. */
export type AgentDef = {
	key: AgentKind,
	label: string,
	short: string,
	models: string[],
	/**
	 *  Whether this harness is actually wired up to launch today. WIP agents
	 *  (Codex/Cursor/OpenCode) are shown but disabled everywhere they're
	 *  offered — this is the single source of truth for that gate.
	 */
	available: boolean,
};

/**  Which coding agent ("harness") runs a task. */
export type AgentKind = "Claude" | "Codex" | "Cursor" | "Opencode";

/**
 *  How a terminal that auto-launches `claude` should (re)launch it, resolved
 *  against the persisted session registry + the on-disk transcript. The frontend
 *  turns this into the shell seed: `--resume <id>` to continue, `--session-id
 *  <id> '<prompt>'` to start fresh, or a plain shell.
 */
export type AgentSession = 
/**  A still-on-disk session to continue: `claude --resume <sessionId>`. */
{ type: "resume"; sessionId: string } | 
/**  A reserved id to start fresh with: `claude --session-id <sessionId> '<prompt>'`. */
{ type: "fresh"; sessionId: string } | 
/**  No agent session — just a login shell. */
{ type: "shell" };

/**
 *  Per-agent configuration: which executable and default model to use.
 * 
 *  `#[serde(default)]`: a future new field must not fail deserialization of
 *  every settings blob written before that field existed — see `Settings`'s
 *  doc comment for the failure mode this guards against.
 */
export type AgentSetting = {
	key?: AgentKind,
	exec?: string,
	model?: string,
};

/**
 *  What a Claude session is doing right now, derived from its hook events by
 *  `crates/hook` and reconciled against the transcript in `hooks.rs`.
 * 
 *  This is the single definition shared by all three: the hook binary writes
 *  `as_str()` into `session_state.state`, the app parses it back with
 *  [`AgentState::parse`], and the frontend gets a real union type over the
 *  bridge instead of `string`.
 */
export type AgentState = 
/**  The model is working (a prompt was submitted, or the transcript is moving). */
"active" | 
/**
 *  Working, but through a subagent — the main transcript is quiet while a
 *  sidechain advances.
 */
"delegating" | 
/**  Blocked on a permission prompt the user has to answer. */
"permission" | 
/**
 *  Blocked on the user for some other reason (a Notification with no
 *  recognized subtype).
 */
"waiting" | 
/**  Alive but quiet — the turn ended and nothing is running. */
"idle" | 
/**  The session ended (SessionEnd). */
"exited";

/**
 *  One entry in a worktree's working-tree status — a file with uncommitted
 *  changes, as shown in the commit box. `staged` reflects whether the index
 *  holds changes for the file (the commit box stages whole files).
 */
export type ChangedFile = {
	path: string,
	/**  Original path for renames. */
	oldPath: string | null,
	status: FileStatus,
	staged: boolean,
	addLines: number,
	delLines: number,
	/**  Binary / non-text content — the diff viewer skips rendering these. */
	binary: boolean,
};

/**
 *  A single annotation a check run emitted (compiler/lint/test error) — the
 *  actionable "what failed" content GitHub shows inline on the Checks tab. Only
 *  populated for failed check runs.
 */
export type CheckAnnotation = {
	/**  `error` | `warning` | `notice` (GitHub's `annotationLevel`, lowercased). */
	level: string,
	message: string,
	/**  File the annotation is anchored to, when any. */
	path: string | null,
	/**  Start line in `path`, when any. */
	startLine: number | null,
	title: string | null,
	/**  Raw log excerpt GitHub attaches (often the full error block), when any. */
	rawDetails: string | null,
};

/**
 *  A failed check run's job log, sliced to the failing step and split into
 *  visible lines + collapsible groups. `truncated` is set when the step's log
 *  exceeded the line cap and only its tail (where the error is) was kept — the UI
 *  notes that earlier lines live on GitHub.
 */
export type CheckLog = {
	blocks: CheckLogBlock[],
	truncated: boolean,
};

/**
 *  One rendered block of a check run's log, mirroring how GitHub's Actions UI
 *  shows an expanded step: loose output is always visible; each `##[group]`
 *  section collapses behind its title. A discriminated union (`kind`) so the
 *  frontend can render + collapse it directly.
 */
export type CheckLogBlock = 
/**
 *  A standalone line — loose step output or a top-level error/warning. Always
 *  visible.
 */
{ kind: "line"; text: string; level: CheckLogLevel } | 
/**
 *  A `##[group]` section — collapsed behind its `title` by default. Nested
 *  sub-groups are flattened into `lines` as plain command lines.
 */
{ kind: "group"; title: string; lines: CheckLogLine[] };

/**
 *  How one raw-log line is classified — drives its tint and whether it stays
 *  expanded by default. Mirrors the `##[error]` / `##[warning]` / `##[group]`
 *  markers GitHub's Actions runner writes into the log stream.
 */
export type CheckLogLevel = "Error" | "Warning" | 
/**  A `##[group]` / `##[section]` / `##[command]` header — a section title. */
"Command" | "Normal";

/**
 *  One line of a check run's raw job log, with its timestamp stripped and its
 *  runner marker (`##[error]` etc.) parsed off into `level`.
 */
export type CheckLogLine = {
	text: string,
	level: CheckLogLevel,
};

/**  Rolled-up CI/status-check state for a PR's latest commit. */
export type CheckRollup = "Success" | "Failure" | "Pending" | 
/**  No checks configured (GitHub returned null). */
"None";

/**  Normalized status of a single CI check (a check run or a status context). */
export type CheckStatus = "Success" | "Failure" | 
/**  Queued / in-progress / expected. */
"Pending" | "Skipped" | 
/**  Neutral / cancelled / action-required — finished without pass/fail. */
"Neutral";

/**
 *  One step of a GitHub Actions check run (e.g. "Run tests"). Only populated for
 *  failed check runs — the expandable detail shows which step broke.
 */
export type CheckStep = {
	number: number,
	name: string,
	status: CheckStatus,
};

export type CmdError = string;

/**  Where a PR comment originated, so the UI can label/anchor it. */
export type CommentKind = 
/**  A top-level conversation comment. */
"Issue" | 
/**  A review summary (approve / request-changes / comment). */
"Review" | 
/**  An inline comment anchored to a file in a review thread. */
"ReviewThread";

/**
 *  The old (HEAD) and new (working-tree) full contents of a file, used by the
 *  diff viewer to expand unchanged context above/below a hunk (GitHub-style).
 *  Either side is empty when it doesn't exist (added vs. deleted).
 */
export type FileSource = {
	oldText: string,
	newText: string,
};

/**  Whether a changed file was added, modified, deleted, renamed, or is untracked. */
export type FileStatus = "Added" | "Modified" | "Deleted" | "Renamed" | "Untracked";

/**
 *  The `gh` CLI integration status, shown in Settings → Integrations. GitHub
 *  powers PR creation and the Reviews dashboard and can't be turned off, so the
 *  UI surfaces whether the CLI is installed and authenticated (and as whom)
 *  rather than a toggle. Auth is borrowed from `gh`'s own session — the CLI owns
 *  it — by reading `gh auth token` and the REST `/user` endpoint.
 */
export type GithubStatus = {
	/**  Whether the `gh` CLI was found on the user's PATH (login-shell resolved). */
	installed: boolean,
	/**  Absolute path to the resolved `gh` executable. Empty when not found. */
	detectedExec: string,
	/**
	 *  The `gh` version line, e.g. "gh version 2.62.0 (2024-11-14)". Empty when
	 *  not found.
	 */
	version: string,
	/**  Whether `gh` has a valid authenticated session. */
	authenticated: boolean,
	/**  Signed-in account login, e.g. "octocat". Empty when not authenticated. */
	account: string,
	/**  The account's display name when set on the GitHub profile. Empty otherwise. */
	name: string,
	/**  The host the session authenticates against, e.g. "github.com". */
	host: string,
};

/**  Which trackers/services are connected. */
export type Integrations = {
	linear?: boolean,
	triage?: boolean,
};

/**  A connected Linear organization. */
export type LinearOrg = {
	slug: string,
	name: string,
};

/**  Linear connection status surfaced to the UI for a given repo. */
export type LinearStatus = {
	/**  True when at least one org is connected. */
	authenticated: boolean,
	/**  The slug of the org this repo uses (its own link, or the only/first org). */
	orgSlug: string | null,
	/**  Display name of that org. */
	org: string | null,
};

/**
 *  The merge queue for a repo's target branch — the ordered list of PRs waiting
 *  to merge, for the Reviews tab's merge-queue panel.
 */
export type MergeQueue = {
	/**  "owner/name" of the repo whose queue this is. */
	repo: string,
	/**  The branch the queue merges into (its default branch). */
	branch: string,
	entries: MergeQueueEntry[],
};

/**  One pull request sitting in a repo's merge queue, in queue order. */
export type MergeQueueEntry = {
	/**
	 *  1-indexed rank in the queue (front of the line = 1), derived from queue
	 *  order rather than GitHub's raw `position` so it's display-ready.
	 */
	position: number,
	state: MergeQueueState,
	prNumber: number,
	prTitle: string,
	prUrl: string,
	author: string,
	authorAvatarUrl: string,
	/**
	 *  True when the viewer authored this PR — highlighted in the panel so they
	 *  can spot their own place in line.
	 */
	isMine: boolean,
};

/**
 *  A merge-queue entry's state (GitHub's `MergeQueueEntryState`). Drives the
 *  per-row status dot in the merge-queue panel.
 */
export type MergeQueueState = 
/**  Waiting its turn (or for the entries ahead to merge). */
"Queued" | 
/**  Required checks are still running against the merge-queue branch. */
"AwaitingChecks" | 
/**  Checks passed; ready to merge when it reaches the front. */
"Mergeable" | 
/**  Cannot merge (failing checks / conflicts) — will be dropped from the queue. */
"Unmergeable" | 
/**  Locked by the queue (a solo/jump entry is being processed). */
"Locked" | 
/**  Any state GitHub adds later that we don't map yet. */
"Unknown";

/**  Token usage attributed to one model, summed across every session. */
export type ModelUsage = {
	/**
	 *  Raw model id from the transcript, e.g. `claude-opus-4-8` — the frontend
	 *  maps it to a family label + color.
	 */
	model: string,
	totals: UsageTotals,
};

/**  The result of creating a PR: its number and web URL (to open in the browser). */
export type NewPr = {
	number: number,
	url: string,
};

/**  An external app/location a worktree can be opened in (Conductor-style menu). */
export type Opener = {
	/**  Stable key passed back to `open_in_app` (e.g. "finder", "cursor"). */
	key: string,
	label: string,
	/**  Whether the app was found installed on this machine. */
	available: boolean,
};

/**  One CI check on a PR's head commit (a GitHub check run or a status context). */
export type PrCheck = {
	name: string,
	status: CheckStatus,
	/**
	 *  The app/workflow that produced it (e.g. "GitHub Actions"), or the status
	 *  context's description — shown as a subtitle.
	 */
	description: string | null,
	/**  Link to the check's details (the run/build page). */
	url: string | null,
	/**  The run's steps — populated only for failed check runs (empty otherwise). */
	steps: CheckStep[],
	/**  Error/warning annotations — populated only for failed check runs. */
	annotations: CheckAnnotation[],
	/**
	 *  The GitHub Actions job id (parsed from `detailsUrl`), when this is an
	 *  Actions check run — lets the UI lazily fetch the job's raw log on expand.
	 *  `None` for status contexts / any check whose URL isn't an Actions job.
	 *  `f64` because Specta forbids 64-bit ints; job ids are exact in an `f64`.
	 */
	jobId: number | null,
};

/**  One comment in a PR's conversation (issue comment, review, or inline thread). */
export type PrComment = {
	author: string,
	authorAvatarUrl: string,
	body: string,
	createdAt: string,
	kind: CommentKind,
	/**  File path for inline (`ReviewThread`) comments; `None` otherwise. */
	path: string | null,
};

/**  The detail panel payload for a selected PR: body, conversation, diff, checks. */
export type PrDetail = {
	body: string,
	/**  The labels ("tags") currently assigned to the PR. */
	labels: PrLabel[],
	/**
	 *  Top-level conversation: issue comments and review summaries, chronological.
	 *  Inline review-thread comments live in `threads`, not here.
	 */
	comments: PrComment[],
	/**  Inline review-comment threads, anchored to files/lines (shown in the diff). */
	threads: PrThread[],
	files: PrFile[],
	/**
	 *  True when the PR has more changed files than we fetched (GitHub allows up
	 *  to 3000; `github.rs` stops at `PR_FILES_CAP`). The UI must say so — a
	 *  reviewer who marks every listed file "Viewed" on a truncated list has
	 *  approved a diff they never saw.
	 */
	filesTruncated: boolean,
	checks: PrCheck[],
	/**
	 *  Commit OID of the PR's base (old side) — used to fetch full file content
	 *  on demand so the diff can expand unchanged context (GitHub-style). Empty
	 *  when `gh` isn't authenticated.
	 */
	baseSha: string,
	/**  Commit OID of the PR's head (new side) — the other end of the expand fetch. */
	headSha: string,
};

/**  A proposed PR (title + body) for the create-PR dialog, before it's opened. */
export type PrDraft = {
	title: string,
	body: string,
	/**  The branch the PR would merge into (shown for confirmation). */
	baseBranch: string,
};

/**  One changed file in a PR, with its unified diff hunk (from the REST files API). */
export type PrFile = {
	path: string,
	/**
	 *  GitHub's status string: "added" | "removed" | "modified" | "renamed" |
	 *  "copied" | "changed" | "unchanged". Kept as a string, not an enum: it's
	 *  display-only, and an unrecognised value should tint like a modification
	 *  rather than fail the whole PR's file list to deserialize.
	 */
	status: string,
	additions: number,
	deletions: number,
	/**  Unified diff for the file; `None` for binary files (no textual patch). */
	patch: string | null,
	/**
	 *  Blob SHA of the file at the PR's head. It changes only when the file's
	 *  *content* changes, so the "Viewed" feature keys its persisted mark on it:
	 *  a mark stored against this SHA survives commits that don't touch the file,
	 *  and auto-clears the moment a new commit changes the file (SHA differs).
	 */
	sha: string,
};

/**
 *  A GitHub label ("tag") — its name plus 6-hex color (no leading `#`, as GitHub
 *  returns it; the frontend prepends it). Used both for a PR's own labels and for
 *  the repo's full label palette in the picker.
 */
export type PrLabel = {
	name: string,
	/**  6-hex color without a leading `#`. */
	color: string,
	/**  The label's description, when set (shown in the picker). */
	description: string | null,
};

/**  The merge state of a worktree's pull request. */
export type PrState = "Open" | "Merged" | "Closed";

/**
 *  One inline review-comment thread on a PR, anchored to a file (and usually a
 *  line). Its comments are rendered together, and resolved threads collapse in the
 *  UI (GitHub-style). Distinct from the top-level `PrComment`s in [`PrDetail`],
 *  which are the issue-level conversation.
 */
export type PrThread = {
	path: string,
	/**
	 *  Line the thread is anchored to (in the file named by `path`). `None` when
	 *  GitHub can't place it anymore (outdated threads on since-changed lines).
	 */
	line: number | null,
	/**
	 *  Which side of the diff the anchor line lives on: `true` = the new/right
	 *  side (an added/context line), `false` = the old/left side (a removed line).
	 */
	onRight: boolean,
	isResolved: boolean,
	/**
	 *  The thread's anchor line no longer matches the current diff (the code moved
	 *  or changed under it). Such threads can't be shown inline in the diff.
	 */
	isOutdated: boolean,
	comments: PrComment[],
};

export type Priority = "Urgent" | "High" | "Medium" | "Low" | 
/**
 *  Linear's "no priority" (numeric 0). Distinct from `Low` so unprioritized
 *  issues don't masquerade as low-priority; the UI shows no priority pill.
 */
"None";

/**
 *  An editable AI prompt for the Settings → Prompts composer: its identity, the
 *  default source, the user's override for the queried scope (if any), the
 *  variable catalog, and the live composition links (what it includes / is
 *  included by).
 */
export type PromptInfo = {
	/**  Stable template name, e.g. `work` (also the `{% include %}` target). */
	name: string,
	/**  Human label for the editor list, e.g. "Work / start task". */
	label: string,
	description: string,
	kind: PromptKind,
	/**
	 *  False for user-created blocks — they have no embedded default and can be
	 *  deleted (their content lives entirely in the DB).
	 */
	builtin: boolean,
	/**  The default template source (the reset target). Empty for custom blocks. */
	default: string,
	/**
	 *  The user's stored override for the queried scope, or `None` when the
	 *  scope inherits (app default or built-in).
	 */
	overrideSource: string | null,
	variables: PromptVar[],
	/**
	 *  Names of prompts this one currently `{% include %}`s (scanned from its
	 *  effective source at the queried scope).
	 */
	includes: string[],
	/**  Names of prompts that currently include this one (reverse of `includes`). */
	usedBy: string[],
};

/**  Whether an editable prompt runs a flow or is a reusable partial. */
export type PromptKind = 
/**  A prompt that drives a flow: Work, Commit, PR, Fix-CI. */
"flow" | 
/**
 *  A reusable partial embedded by flows via `{% include %}` — the built-in
 *  `issue` context or a user-created block.
 */
"block";

/**
 *  The result of rendering a draft prompt against representative sample data —
 *  either the rendered text or the render/compile error, for the live preview.
 */
export type PromptPreview = {
	output: string,
	/**  The minijinja error when the draft doesn't compile/render, else `None`. */
	error: string | null,
};

/**
 *  One documented variable a prompt template receives, shown in the editor's
 *  variable palette so users know what they can reference.
 */
export type PromptVar = {
	/**  The reference name, e.g. `ticket_id` (used as `{{ ticket_id }}`). */
	name: string,
	description: string,
};

/**  A connected repository / task-tracker pairing. */
export type Repo = {
	name: string,
	tracker: string,
	/**  Number of agents currently active on this repo. */
	agents: number,
	/**
	 *  Absolute path on disk of the repo's git checkout. Always set in
	 *  practice — every repo is registered via `repo::add`, which validates a
	 *  real local folder before inserting — but stays `Option` because the
	 *  underlying `repos.path` column is nullable (a leftover from before
	 *  migration `0002_repo_path` and the removed built-in seed repos).
	 */
	path: string | null,
};

/**  GitHub's aggregate review decision for a PR. */
export type ReviewDecision = "Approved" | "ChangesRequested" | 
/**  A review is required but none satisfying it has been given yet. */
"ReviewRequired" | 
/**  No review has been requested/required (or GitHub returned null). */
"None";

/**  The categorized PR inbox for the Reviews tab, scoped to one org. */
export type ReviewInbox = {
	/**  PRs the viewer authored (grouped by repo on the frontend). */
	mine: ReviewPr[],
	/**  PRs where the viewer is individually requested as a reviewer. */
	requested: ReviewPr[],
	/**  PRs requested via a team the viewer is on — one section per team. */
	teams: TeamReviews[],
};

/**
 *  A pull request shown in the Reviews dashboard. Spans repos within one org, so
 *  it carries its own `repo` (owner/name) rather than relying on a single active
 *  checkout the way [`WorktreePr`] does.
 */
export type ReviewPr = {
	/**  GraphQL node id — stable selection key across refetches. */
	id: string,
	number: number,
	title: string,
	url: string,
	/**  "owner/name" the PR lives in (the grouping axis for "My PRs"). */
	repo: string,
	/**  The PR's head branch name (shown in the header, click-to-copy). */
	headRef: string,
	author: string,
	authorAvatarUrl: string,
	state: PrState,
	isDraft: boolean,
	reviewDecision: ReviewDecision,
	checks: CheckRollup,
	/**
	 *  True when the PR is sitting in the repo's merge queue (GitHub's "Queued"
	 *  badge). The exact queue position isn't carried — it's shown in the
	 *  merge-queue bot comment rendered in the PR conversation.
	 */
	isInMergeQueue: boolean,
	additions: number,
	deletions: number,
	commentCount: number,
	/**  Reviewers requested on the PR (people and teams). */
	reviewers: Reviewer[],
	/**  ISO-8601 timestamp of the last update. */
	updatedAt: string,
};

/**
 *  A file's persisted "Viewed" mark in the Reviews tab: the file path plus the
 *  blob SHA it was marked at. The UI treats a file as reviewed only while its
 *  current [`PrFile::sha`] still equals this `sha` — so a new commit that changes
 *  the file (new SHA) automatically drops it back to unreviewed.
 */
export type ReviewedFile = {
	path: string,
	sha: string,
};

/**  A reviewer requested on a PR — a person (with avatar) or a team (no avatar). */
export type Reviewer = {
	kind: ReviewerKind,
	/**  Login for a user, team name for a team. */
	name: string,
	/**  Avatar URL for users; empty for teams. */
	avatarUrl: string,
};

/**  Whether a requested reviewer is an individual or a team. */
export type ReviewerKind = "User" | "Team";

/**  The repo's `.santree/init.sh` setup script, surfaced to the Settings editor. */
export type ScriptInfo = {
	path: string,
	exists: boolean,
	/**  Whether the file has its executable bit set (required to run on create). */
	executable: boolean,
	content: string,
};

/**
 *  The current state of one Claude session, captured live via the hooks santree
 *  injects into its `claude` launches. One per session id (a current-state row,
 *  not an event log). The frontend correlates a session back to a worktree later
 *  via `cwd` / the `terminal_sessions` mapping.
 *  Only `PartialEq` (not `Eq`) because of the `f64` timestamp below.
 */
export type SessionState = {
	/**  Claude session id (the one santree minted via `--session-id`). */
	sessionId: string,
	/**  Derived agent state. */
	state: AgentState,
	/**
	 *  Raw Claude hook event that last set `state` (e.g. "Stop"). Deliberately a
	 *  free string, not an enum: it's Claude's vocabulary, not ours, and a new
	 *  event name from a CLI upgrade must not fail to deserialize.
	 */
	event: string,
	/**  Working directory the session ran in (the worktree path). */
	cwd: string,
	/**  Notification message, when the last event carried one. */
	message: string | null,
	/**  Transcript path on disk, when the payload carried one. */
	transcriptPath: string | null,
	/**  Epoch ms the state was last updated — raw, formatted live by the frontend. */
	updatedAtMs: number | null,
};

/**
 *  "A session's state changed" — the frontend invalidates its session-states
 *  query and refetches. Empty payload: the table is tiny, so a bare signal is
 *  enough (mirrors how `WorktreeChanged` drives a targeted invalidation).
 */
export type SessionStateChanged = Record<string, never>;

/**
 *  Token usage for one Claude session (one main transcript), plus its current
 *  context-window fill — the "how much before compaction" signal.
 */
export type SessionUsage = {
	/**  The session id (the transcript file's stem, a UUID). */
	sessionId: string,
	/**
	 *  The owning repository (folder) the session ran in — the grouping key in the
	 *  Usage panel. Resolved from the transcript's `cwd` against santree's
	 *  registered repos, falling back to the path.
	 */
	repo: string,
	/**
	 *  The worktree label (the issue id under `.santree/worktrees/`) when the
	 *  session ran in a santree worktree; `None` for the repo's main checkout.
	 */
	worktree: string | null,
	/**  The session's primary (most-used by tokens) model id — the badge model. */
	model: string,
	/**
	 *  Every model used in the session with its own token split, most-used first.
	 *  Surfaces mid-session model switches (a session isn't tied to one model).
	 */
	models: ModelUsage[],
	totals: UsageTotals,
	/**
	 *  Tokens in the last turn's context (input + cache read + cache write) ≈ the
	 *  current context size — what "fills up" before Claude compacts.
	 */
	contextTokens: number | null,
	/**
	 *  The model's context-window limit the fill is measured against (200k, or 1M
	 *  when the observed context already exceeds 200k).
	 */
	contextLimit: number | null,
	/**  Epoch ms of the session's most recent activity — formatted live by the frontend. */
	lastActivityMs: number | null,
};

/**
 *  "A session's live token/context usage changed" — the frontend invalidates its
 *  session-usage-live query. Fired far more often than [`SessionStateChanged`]
 *  (once per status-line render), so it's a *separate* event to avoid refetching
 *  the state table on every status-line tick. The hook tags its socket byte to
 *  pick which one this is.
 */
export type SessionUsageChanged = Record<string, never>;

/**
 *  Live token/context usage for one Claude session, captured from Claude's own
 *  status-line stdin (see crates/hook's `statusline` mode). This is Claude's
 *  authoritative `used_percentage` + token counts — the faithful source for the
 *  inline session status line, unlike the transcript-derived reconstruction in
 *  `usage.rs`. One current-value row per session id.
 */
export type SessionUsageLive = {
	/**  Claude session id (matches [`SessionState::session_id`]). */
	sessionId: string,
	/**
	 *  Claude's pre-calculated context-window fill, 0..100 (raw — the 1.2x
	 *  display nudge is applied at render time, matching the terminal bar).
	 */
	usedPct: number | null,
	/**  Tokens currently in the context window (input + cache reads + writes). */
	inputTokens: number | null,
	/**  The model's context window size in tokens (200k, or 1M for extended). */
	contextSize: number | null,
	/**  Model id, e.g. `claude-opus-4-8` — mapped to a family label by the frontend. */
	model: string,
	/**  Session cost so far in USD (Claude's own `cost.total_cost_usd`). */
	costUsd: number | null,
	/**  Epoch ms this row was last written — raw, formatted live by the frontend. */
	updatedAtMs: number | null,
};

/**
 *  User settings, persisted as a JSON blob in the `settings` table. Seeded from
 *  defaults on first run; edits are written back through `set_settings`.
 * 
 *  `#[serde(default)]` at every level here (this struct + `Integrations` +
 *  `AgentSetting`) matters more than it looks: without it, adding a single new
 *  field in a future release makes every EXISTING stored blob fail to parse.
 *  `get_settings` already falls back to `config::default_settings()` on a parse
 *  error — silently wiping the user's real agent execs/models/integration
 *  toggles — and the next `set_settings` call then *persists* that wipe. With
 *  `#[serde(default)]`, a missing field falls back per-field (via `Default`,
 *  seeded from `config::default_settings()`) instead of the whole blob being
 *  discarded.
 */
export type Settings = {
	defaultAgent?: AgentKind,
	integrations?: Integrations,
	agents?: AgentSetting[],
};

/**
 *  A streamed setup-script event for the Trees "Setup" tab. `Line` is a committed
 *  output line (appended). `Progress` is a transient redraw of the current line —
 *  emitted when the script's output ends a line with a lone `\r` (progress bars,
 *  spinners) — which the view shows in place so a redrawing bar reads as movement
 *  instead of a frozen log. A final `Done` closes the tab.
 */
export type SetupEvent = { type: "line"; text: string } | { type: "progress"; text: string } | { type: "done"; ok: boolean };

/**
 *  What an extra Trees main-area tab hosts: a Claude agent session (resumable
 *  across app restarts via its stored session id) or a plain login shell.
 */
export type TabKind = "claude" | "terminal" | 
/**
 *  A Claude session dedicated to fixing a PR's failing CI: seeded with the
 *  failed log + guardrails, launched with a commit/push-denying settings file.
 *  Persisted like a Claude tab (resumable), but its pane always applies the
 *  no-git guardrail — even on resume after a restart.
 */
"fixCi";

/**  A ticket in the dependency graph. `x`/`y` are its canvas position. */
export type Task = {
	id: string,
	title: string,
	project: string,
	/**
	 *  The project's color (hex) as configured in Linear, when it has one. Falls
	 *  back to the frontend's per-name color map when absent.
	 */
	projectColor: string | null,
	/**
	 *  The project's icon — an emoji (rendered directly) or a Linear icon name
	 *  (we don't ship that icon set, so it falls back to the colored dot).
	 */
	projectIcon: string | null,
	status: TaskStatus,
	ready: boolean,
	blockedBy: string[],
	/**
	 *  Whether this ticket is directly actionable by the viewer: assigned to
	 *  them and not yet done. Non-actionable tickets (someone else's, or
	 *  already done) are pulled into the graph only as blocker context and are
	 *  rendered grayed out.
	 */
	actionable: boolean,
	/**
	 *  The assignee's display name, when the issue is assigned (shown in the
	 *  inspector's dependency cards).
	 */
	assignee: string | null,
	/**  The assignee's avatar URL, when present. */
	assigneeAvatarUrl: string | null,
	x: number,
	y: number,
};

/**  Lifecycle status of a ticket / worktree. */
export type TaskStatus = "InReview" | "InProgress" | "Todo" | "Backlog" | 
/**
 *  A custom "Blocked" workflow state (Linear has no native `blocked` type, so
 *  teams model it as an `unstarted`/`started` state named "Blocked"). Never
 *  startable — being in this state is itself a not-actionable signal,
 *  independent of any ticket-to-ticket blocker relations.
 */
"Blocked" | 
/**
 *  Completed or canceled. Only appears on non-actionable blocker context
 *  nodes — the viewer's own assigned issues never include done work.
 */
"Done";

/**  Review requests waiting on a specific team the viewer belongs to. */
export type TeamReviews = {
	slug: string,
	name: string,
	prs: ReviewPr[],
};

/**
 *  How the frontend asks for a new terminal. An empty `command` means the user's
 *  login shell.
 */
export type TerminalOpenOpts = {
	cwd: string | null,
	command: string,
	args: string[],
	cols: number,
	rows: number,
};

/**  A comment on a triage issue (markdown body), with threaded replies. */
export type TriageComment = {
	/**  Linear comment id — used as the `parentId` when posting a reply. */
	id: string,
	author: string,
	/**  Public avatar URL of the author, when they have one. */
	avatarUrl: string | null,
	/**  Epoch ms the comment was posted — raw, formatted live by the frontend. */
	createdAtMs: number | null,
	/**  Markdown — may contain inline images. */
	body: string,
	/**  Threaded replies, in chronological order. */
	children: TriageComment[],
};

/**
 *  The full triage issue as rendered in the discussion pane: the Linear issue's
 *  description, metadata, and comment thread.
 * 
 *  Only `PartialEq` (not `Eq`) because of the `f64` timestamp fields below.
 */
export type TriageDetail = {
	id: string,
	title: string,
	priority: Priority,
	/**  Workflow state name (e.g. "Triage"). */
	state: string,
	/**  Id of the current workflow state (for the status picker's selection). */
	stateId: string | null,
	/**  All workflow states the issue can move to, ordered as in Linear. */
	states: WorkflowState[],
	/**  Canonical Linear URL for the issue. */
	url: string,
	author: string,
	/**  Public avatar URL of the issue creator, when they have one. */
	authorAvatarUrl: string | null,
	/**  Epoch ms the issue was created — raw, formatted live by the frontend. */
	createdAtMs: number | null,
	labels: string[],
	project: string | null,
	/**  Absolute epoch ms the issue's SLA breaches, if it has one. */
	slaBreachMs: number | null,
	/**  Epoch ms the issue is snoozed until, if snoozed. */
	snoozedUntilMs: number | null,
	/**  Markdown description — may contain inline images. */
	description: string,
	comments: TriageComment[],
};

/**  The team triage rotation surfaced from Linear's triage responsibility. */
export type TriageSchedule = {
	team: string,
	scheduleName: string,
	currentName: string | null,
	/**  Avatar of whoever is currently on triage, when available. */
	currentAvatarUrl: string | null,
	/**  True when the signed-in viewer is the one currently on triage. */
	currentIsMe: boolean,
	shifts: TriageShift[],
};

/**  A single on-call slot in a triage rotation. */
export type TriageShift = {
	name: string,
	/**  Avatar of the person on this shift, when Linear exposes one. */
	avatarUrl: string | null,
	/**  Human time range, e.g. "Mon–Wed". */
	range: string,
	isCurrent: boolean,
	isMe: boolean,
};

/**
 *  An untriaged ticket awaiting investigation (the queue row).
 * 
 *  Only `PartialEq` (not `Eq`) because of the `f64` timestamp fields below —
 *  nothing here needs `TriageTicket` as a map/set key.
 */
export type TriageTicket = {
	id: string,
	title: string,
	priority: Priority,
	/**
	 *  Epoch ms the issue was created. Raw, not a pre-formatted "5m ago" label —
	 *  with triage's multi-minute query staleTime, a label baked in at fetch
	 *  time would freeze between refetches. The frontend formats (and ticks)
	 *  it live; see `src/lib/relativeTime.ts`. `f64` (not `i64`) because Specta
	 *  forbids exporting 64-bit ints to TypeScript; epoch-ms values are exact
	 *  in an `f64` for millennia to come.
	 */
	createdAtMs: number | null,
	meta: string,
	/**
	 *  The team key (e.g. "MSG"), used to group the queue when the viewer is on
	 *  more than one team.
	 */
	team: string | null,
	/**
	 *  Absolute epoch ms the issue's SLA breaches, if it has one. `None` when
	 *  the issue has no SLA. The frontend renders (and ticks) the countdown.
	 */
	slaBreachMs: number | null,
	/**
	 *  Epoch ms the issue is snoozed until, if snoozed; the UI greys it out and
	 *  sinks it to the bottom of the queue.
	 */
	snoozedUntilMs: number | null,
	/**
	 *  Whether the issue is assigned to the viewer. The queue defaults to the
	 *  viewer's own issues; others' are shown only when "be a good citizen" is on.
	 */
	mine: boolean,
};

/**
 *  Debounced "a Claude transcript changed on disk" signal. The frontend reacts by
 *  invalidating the usage query so the panel refetches without polling.
 */
export type UsageChanged = Record<string, never>;

/**
 *  Progress of the (cold) transcript parse in file counts, so the panel can show a
 *  determinate progress bar on the first load. Only fires while the per-file cache
 *  is cold — a warm reload returns instantly and emits nothing meaningful.
 */
export type UsageProgress = {
	done: number,
	total: number,
};

/**
 *  The full Claude usage report: grand + period totals, the per-model split, and
 *  the most recent sessions (newest first).
 */
export type UsageReport = {
	total: UsageTotals,
	today: UsageTotals,
	week: UsageTotals,
	month: UsageTotals,
	byModel: ModelUsage[],
	sessions: SessionUsage[],
};

/**
 *  Aggregated Claude token counts for a bucket (a period, a model, or a session).
 *  Every count is a raw number the frontend formats; the four token classes are
 *  kept apart because they're priced differently. `cost_usd` is *derived* from a
 *  static price table and is approximate — the token counts themselves are exact.
 *  Counts are `f64` (not `u64`) to match the domain's "numbers cross the bridge as
 *  JS numbers" convention; token totals stay well within f64's exact-integer range.
 */
export type UsageTotals = {
	inputTokens: number | null,
	outputTokens: number | null,
	cacheReadTokens: number | null,
	cacheWriteTokens: number | null,
	costUsd: number | null,
};

/**
 *  A workflow state an issue can move to (one of its team's states). Moving an
 *  issue out of the `triage` state — e.g. into `backlog`/`unstarted` — is how the
 *  UI "promotes" a triage item.
 */
export type WorkflowState = {
	id: string,
	name: string,
	/**
	 *  Linear state category: triage | backlog | unstarted | started | completed
	 *  | canceled | duplicate.
	 */
	type: string,
	/**  State color (hex), as configured in Linear. */
	color: string,
};

/**  A live git worktree with an agent attached. */
export type Worktree = {
	/**  The issue identifier this worktree was created for (e.g. "AK-165"). */
	id: string,
	title: string,
	/**
	 *  The ticket's status, when the issue is one santree knows about. `None`
	 *  when there's nothing to know (the base worktree, or a worktree whose
	 *  issue we can't resolve) — the UI renders no chip rather than a made-up one.
	 */
	status: TaskStatus | null,
	addLines: number,
	delLines: number,
	dirty: boolean,
	/**  Commits this branch is ahead of its base. */
	ahead: number,
	/**  Commits this branch is behind its base (origin/<base>). */
	behind: number,
	/**
	 *  Commits on this branch not yet pushed to its remote (what `git push` would
	 *  upload); 0 when the remote is up to date.
	 */
	unpushed: number,
	/**
	 *  Commits on this branch's remote tracking ref not yet local (what `git pull`
	 *  would download — PR-UI suggestions, "Update branch", a teammate's push);
	 *  0 when local is up to date or the branch has no remote.
	 */
	remoteBehind: number,
	/**
	 *  When `remote_behind > 0`, whether pulling origin/<branch> would conflict
	 *  with local commits (from a virtual merge). Disables the Pull button — a
	 *  conflicting pull can't be applied automatically and must be resolved in the
	 *  worktree. Always false when nothing is pending (`remote_behind == 0`).
	 */
	pullConflict: boolean,
	/**
	 *  The agent attached to this worktree, once one has actually been launched
	 *  in it. `None` for the base worktree (no agent concept) and for worktrees
	 *  with no session yet.
	 */
	agent: AgentKind | null,
	/**
	 *  Derived from the worktree's live agent session. `None` when there is no
	 *  session to derive it from — the backend does not guess.
	 */
	activity: Activity | null,
	/**  Git branch checked out in the worktree (e.g. "feature/ak-165-…"). */
	branch: string,
	/**  Absolute filesystem path of the worktree directory. */
	path: string,
	/**  Linear project the issue belongs to, used to group the Trees tabs. */
	project: string | null,
	/**  Branch this worktree was created from. */
	baseBranch: string,
	/**  Whether `.santree/init.sh` has been run for this worktree. */
	setupRan: boolean,
	/**
	 *  True only for the optimistic frontend placeholder shown while a worktree
	 *  is still being created (it has no branch/path yet). The backend always
	 *  sets this to `false` — the `true` case exists only in the frontend's own
	 *  placeholder object (`AppContext.pendingLaunches`), built in JS and never
	 *  deserialized from this type (`Worktree` only derives `Serialize`).
	 */
	pending: boolean,
};

/**
 *  Debounced "a worktree's files changed on disk" signal. The frontend reacts by
 *  invalidating that worktree's status/files/diff queries for the active repo.
 *  `issue_id` is [`BASE_ID`] for a change to the base worktree (the repo root).
 */
export type WorktreeChanged = {
	issueId: string,
};

/**
 *  Live status of the PR opened from a worktree's branch (fetched from GitHub,
 *  separately from the worktree list so the list stays fast/offline-capable).
 */
export type WorktreePr = {
	/**  The worktree this PR belongs to (its issue id). */
	issueId: string,
	number: number,
	url: string,
	state: PrState,
};

/**
 *  An extra main-area tab in Trees (opened via the "+" menu), persisted so it
 *  survives an app restart. Claude tabs re-resolve their stored session on open
 *  (`terminal_sessions`, term_key `tree:<worktree_id>:tab:<id>`); terminal tabs
 *  just reopen a fresh shell.
 */
export type WorktreeTab = {
	id: string,
	worktreeId: string,
	kind: TabKind,
	title: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

